<?php
session_start();
include 'db.php';
include '../includes/functions.php';
include 'includes/header.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require_once __DIR__ . '/PHPMailer/src/PHPMailer.php';
require_once __DIR__ . '/PHPMailer/src/Exception.php';
require_once __DIR__ . '/PHPMailer/src/SMTP.php';
require_once __DIR__ . '/TCPDF/tcpdf.php';

// Create tables if not exist
$conn->query("CREATE TABLE IF NOT EXISTS advance_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    monthly_deduction DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_by INT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$conn->query("CREATE TABLE IF NOT EXISTS advances (
    id INT AUTO_INCREMENT PRIMARY KEY,
    loan_officer_id INT NOT NULL,
    loan_officer_name VARCHAR(255) NOT NULL,
    template_id INT DEFAULT NULL,
    amount DECIMAL(12,2) NOT NULL,
    balance DECIMAL(12,2) NOT NULL,
    start_date DATE NOT NULL,
    monthly_deduction DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    duration_months INT NOT NULL DEFAULT 1,
    recorded_by INT DEFAULT NULL,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$advanceDurationCheck = $conn->query("SHOW COLUMNS FROM advances LIKE 'duration_months'");
if ($advanceDurationCheck && $advanceDurationCheck->num_rows === 0) {
    $conn->query("ALTER TABLE advances ADD COLUMN duration_months INT NOT NULL DEFAULT 1");
}

$conn->query("CREATE TABLE IF NOT EXISTS advance_repayments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    advance_id INT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    payment_date DATE NOT NULL,
    recorded_by INT DEFAULT NULL,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$conn->query("CREATE TABLE IF NOT EXISTS advance_repayment_schedule (
    id INT AUTO_INCREMENT PRIMARY KEY,
    advance_id INT NOT NULL,
    due_amount DECIMAL(12,2) NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$messages = [];

function generate_advance_schedule_pdf($loan_officer_name, $amount, $duration, $monthly, $start_date, $scheduleRows) {
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
    $pdf->SetCreator('Inua Premium Services');
    $pdf->SetAuthor('Inua Premium Services');
    $pdf->SetTitle('Advance Repayment Schedule');
    $pdf->SetMargins(15, 20, 15);
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 8, 'Advance Repayment Schedule', 0, 1, 'C');
    $pdf->Ln(4);

    $pdf->SetFont('helvetica', '', 10);
    $pdf->Cell(0, 6, 'Loan Officer: ' . $loan_officer_name, 0, 1);
    $pdf->Cell(0, 6, 'Advance Amount: KES ' . number_format($amount, 2), 0, 1);
    $pdf->Cell(0, 6, 'Duration: ' . intval($duration) . ' months', 0, 1);
    $pdf->Cell(0, 6, 'Monthly Deduction: KES ' . number_format($monthly, 2), 0, 1);
    $pdf->Cell(0, 6, 'Start Date: ' . date('d-m-Y', strtotime($start_date)), 0, 1);
    $pdf->Ln(6);

    $pdf->SetFont('helvetica', 'B', 11);
    $pdf->SetFillColor(232, 69, 69);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(45, 8, 'Amount Due', 1, 0, 'C', 1);
    $pdf->Cell(45, 8, 'Amount Deducted', 1, 0, 'C', 1);
    $pdf->Cell(45, 8, 'Balance', 1, 0, 'C', 1);
    $pdf->Cell(45, 8, 'Repayment Date', 1, 1, 'C', 1);

    $pdf->SetTextColor(33, 37, 41);
    $pdf->SetFont('helvetica', '', 10);
    foreach ($scheduleRows as $row) {
        $rowBalance = isset($row['balance']) ? $row['balance'] : 0.00;
        $rowPaid = isset($row['paid']) ? $row['paid'] : 0.00;
        $rowDue = isset($row['amount_due']) ? $row['amount_due'] : 0.00;
        $pdf->Cell(45, 8, 'KES ' . number_format($rowDue, 2), 1, 0, 'R');
        $pdf->Cell(45, 8, 'KES ' . number_format($rowPaid, 2), 1, 0, 'R');
        $pdf->Cell(45, 8, 'KES ' . number_format($rowBalance, 2), 1, 0, 'R');
        $pdf->Cell(45, 8, $row['repayment_date'] ?? '', 1, 1, 'C');
    }

    $pdf->Ln(6);
    $pdf->SetFont('helvetica', 'I', 8);
    $pdf->SetTextColor(56, 152, 219);
    $pdf->Cell(0, 6, 'Generated by Inua Premium Services', 0, 1, 'C');

    return $pdf->Output('', 'S');
}

function send_pdf_email($recipient_email, $subject, $body, $pdf_content, $filename) {
    try {
        $emailCredentials = getEmailAccount();
        if (empty($emailCredentials['sender_email']) || empty($emailCredentials['app_password'])) {
            throw new Exception('Email settings are not configured.');
        }

        $mail = new PHPMailer(true);
        $mail->SMTPOptions = [
            'ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true,
            ],
        ];
        $mail->SMTPDebug = 0;
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->Port = 587;
        $mail->SMTPSecure = 'tls';
        $mail->SMTPAuth = true;
        $mail->Username = $emailCredentials['sender_email'];
        $mail->Password = $emailCredentials['app_password'];
        $mail->CharSet = 'UTF-8';
        $mail->setFrom($emailCredentials['sender_email'], 'Inua Premium Services');
        $mail->addAddress($recipient_email);
        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $body;
        $mail->AltBody = strip_tags($body);
        $mail->addStringAttachment($pdf_content, $filename, 'base64', 'application/pdf');
        $mail->send();
        return true;
    } catch (Exception $e) {
        error_log('Email send failed: ' . $e->getMessage());
        return false;
    }
}

// Handlers
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Create template
    if (isset($_POST['create_template'])) {
        $title = trim($_POST['title']);
        $monthly = floatval($_POST['monthly_deduction']);
        $created_by = $_SESSION['user_id'] ?? null;

        $stmt = $conn->prepare("INSERT INTO advance_templates (title, monthly_deduction, created_by) VALUES (?, ?, ?)");
        $stmt->bind_param('sdi', $title, $monthly, $created_by);
        if ($stmt->execute()) {
            $messages[] = 'Template created.';
        } else {
            $messages[] = 'Error creating template: ' . $conn->error;
        }
        $stmt->close();
    }

    // Book advance
    if (isset($_POST['book_advance'])) {
        $loan_officer_id = (int) $_POST['loan_officer_id'];
        $template_id = !empty($_POST['template_id']) ? (int) $_POST['template_id'] : null;
        $amount = floatval($_POST['amount']);
        $monthly = floatval($_POST['monthly_deduction']);
        $duration = max(1, min(36, (int) ($_POST['duration_months'] ?? 1)));
        $start_date = $_POST['start_date'];
        $recorded_by = $_SESSION['user_id'] ?? null;

        // get officer name and email
        $res = $conn->prepare("SELECT name, email FROM users WHERE id = ? LIMIT 1");
        $res->bind_param('i', $loan_officer_id);
        $res->execute();
        $res->bind_result($loan_officer_name, $loan_officer_email);
        $res->fetch();
        $res->close();

        if (empty($loan_officer_name)) {
            $messages[] = 'Loan officer not found.';
        } else {
            if ($monthly <= 0 || $monthly * $duration > $amount) {
                $monthly = round($amount / $duration, 2);
            }
            $balance = $amount;
            $stmt = $conn->prepare("INSERT INTO advances (loan_officer_id, loan_officer_name, template_id, amount, balance, start_date, monthly_deduction, duration_months, recorded_by) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)");
            $stmt->bind_param('isiddsiii', $loan_officer_id, $loan_officer_name, $template_id, $amount, $balance, $start_date, $monthly, $duration, $recorded_by);
            if ($stmt->execute()) {
                $advance_id = $conn->insert_id;
                $messages[] = 'Advance booked successfully.';

                // Generate repayment schedule
                $installment = $monthly;
                $last_amount = round($amount - $monthly * ($duration - 1), 2);
                $due_date = new DateTime($start_date);
                $scheduleStmt = $conn->prepare("INSERT INTO advance_repayment_schedule (advance_id, due_amount, due_date, status) VALUES (?, ?, ?, 'pending')");
                for ($i = 0; $i < $duration; $i++) {
                    if ($i > 0) {
                        $due_date->modify('+1 month');
                    }
                    $due_amount = ($i === $duration - 1) ? $last_amount : $installment;
                    $due_date_str = $due_date->format('Y-m-d');
                    $scheduleStmt->bind_param('ids', $advance_id, $due_amount, $due_date_str);
                    $scheduleStmt->execute();
                }
                $scheduleStmt->close();

                // Send schedule by email
                if (!empty($loan_officer_email)) {
                    $scheduleRows = [];
                    $due_date = new DateTime($start_date);
                    $runningBalance = $amount;
                    for ($i = 0; $i < $duration; $i++) {
                        if ($i > 0) {
                            $due_date->modify('+1 month');
                        }
                        $due_amount = ($i === $duration - 1) ? $last_amount : $installment;
                        $runningBalance -= $due_amount;
                        $scheduleRows[] = [
                            'amount_due' => $due_amount,
                            'paid' => 0.00,
                            'balance' => max(0, $runningBalance),
                            'repayment_date' => $due_date->format('d-m-Y')
                        ];
                    }
                    $pdfContent = generate_advance_schedule_pdf(
                        $loan_officer_name,
                        $amount,
                        $duration,
                        $monthly,
                        $start_date,
                        $scheduleRows
                    );
                    $subject = 'Advance Repayment Schedule';
                    $body = 'Dear ' . htmlspecialchars($loan_officer_name) . ',<br><br>Please find attached your advance repayment schedule.';
                    if (send_pdf_email($loan_officer_email, $subject, $body, $pdfContent, 'advance_schedule.pdf')) {
                        $messages[] = 'Schedule sent to loan officer email.';
                    } else {
                        $messages[] = 'Advance booked, but email send failed.';
                    }
                } else {
                    $messages[] = 'Advance booked; loan officer has no email address.';
                }
            } else {
                $messages[] = 'Error booking advance: ' . $conn->error;
            }
            $stmt->close();
        }
    }

    // Update advance
    if (isset($_POST['update_advance']) && !empty($_POST['edit_advance_id'])) {
        $advance_id = (int) $_POST['edit_advance_id'];
        $loan_officer_id = (int) $_POST['loan_officer_id'];
        $template_id = !empty($_POST['template_id']) ? (int) $_POST['template_id'] : null;
        $amount = floatval($_POST['amount']);
        $monthly = floatval($_POST['monthly_deduction']);
        $duration = max(1, min(36, (int) ($_POST['duration_months'] ?? 1)));
        $start_date = $_POST['start_date'];
        $recorded_by = $_SESSION['user_id'] ?? null;

        $res = $conn->prepare("SELECT name FROM users WHERE id = ? LIMIT 1");
        $res->bind_param('i', $loan_officer_id);
        $res->execute();
        $res->bind_result($loan_officer_name);
        $res->fetch();
        $res->close();

        if (empty($loan_officer_name)) {
            $messages[] = 'Loan officer not found.';
        } else {
            $paidQ = $conn->prepare("SELECT IFNULL(SUM(amount), 0) FROM advance_repayments WHERE advance_id = ?");
            $paidQ->bind_param('i', $advance_id);
            $paidQ->execute();
            $paidQ->bind_result($total_paid);
            $paidQ->fetch();
            $paidQ->close();

            $balance = max(0, $amount - $total_paid);
            $upd = $conn->prepare("UPDATE advances SET loan_officer_id = ?, loan_officer_name = ?, template_id = ?, amount = ?, balance = ?, start_date = ?, monthly_deduction = ?, duration_months = ?, recorded_by = ? WHERE id = ?");
            $upd->bind_param('isiddsiiii', $loan_officer_id, $loan_officer_name, $template_id, $amount, $balance, $start_date, $monthly, $duration, $recorded_by, $advance_id);
            if ($upd->execute()) {
                $messages[] = 'Advance updated successfully.';
                $del = $conn->prepare("DELETE FROM advance_repayment_schedule WHERE advance_id = ?");
                $del->bind_param('i', $advance_id);
                $del->execute();
                $del->close();

                $remaining = max(0, $amount - $total_paid);
                if ($remaining > 0) {
                    $installment = $monthly;
                    if ($installment <= 0 || $installment * $duration > $remaining) {
                        $installment = round($remaining / $duration, 2);
                    }
                    $last_amount = round($remaining - $installment * ($duration - 1), 2);
                    $due_date = new DateTime($start_date);
                    $scheduleStmt = $conn->prepare("INSERT INTO advance_repayment_schedule (advance_id, due_amount, due_date, status) VALUES (?, ?, ?, 'pending')");
                    for ($i = 0; $i < $duration; $i++) {
                        if ($i > 0) {
                            $due_date->modify('+1 month');
                        }
                        $due_amount = ($i === $duration - 1) ? $last_amount : $installment;
                        $due_date_str = $due_date->format('Y-m-d');
                        $scheduleStmt->bind_param('ids', $advance_id, $due_amount, $due_date_str);
                        $scheduleStmt->execute();
                    }
                    $scheduleStmt->close();
                }
            } else {
                $messages[] = 'Error updating advance: ' . $conn->error;
            }
            $upd->close();
        }
    }

    // Add repayment
    if (isset($_POST['add_repayment'])) {
        $advance_id = (int) $_POST['advance_id'];
        $rep_amount = floatval($_POST['repayment_amount']);
        $payment_date = $_POST['payment_date'];
        $recorded_by = $_SESSION['user_id'] ?? null;

        $stmt = $conn->prepare("INSERT INTO advance_repayments (advance_id, amount, payment_date, recorded_by) VALUES (?, ?, ?, ?)");
        $stmt->bind_param('idsi', $advance_id, $rep_amount, $payment_date, $recorded_by);
        if ($stmt->execute()) {
            $upd = $conn->prepare("UPDATE advances SET balance = balance - ? WHERE id = ?");
            $upd->bind_param('di', $rep_amount, $advance_id);
            $upd->execute();
            $upd->close();

            // get loan officer details and current balance
            $q = $conn->prepare("SELECT a.loan_officer_name, u.email, a.amount, a.balance FROM advances a LEFT JOIN users u ON a.loan_officer_id = u.id WHERE a.id = ? LIMIT 1");
            $q->bind_param('i', $advance_id);
            $q->execute();
            $q->bind_result($loan_officer_name, $loan_officer_email, $advance_amount, $advance_balance);
            $q->fetch();
            $q->close();

            if (!empty($loan_officer_email)) {
                $scheduleRows = [];
                $scheduleRows[] = [
                    'amount_due' => $rep_amount,
                    'paid' => $rep_amount,
                    'balance' => $advance_balance,
                    'repayment_date' => date('d-m-Y', strtotime($payment_date))
                ];

                $runningBalance = $advance_balance;
                $scheduleQuery = $conn->prepare("SELECT due_amount, due_date FROM advance_repayment_schedule WHERE advance_id = ? ORDER BY due_date ASC");
                $scheduleQuery->bind_param('i', $advance_id);
                $scheduleQuery->execute();
                $scheduleResult = $scheduleQuery->get_result();
                while ($row = $scheduleResult->fetch_assoc()) {
                    $scheduleRows[] = [
                        'amount_due' => $row['due_amount'],
                        'paid' => 0.00,
                        'balance' => max(0, $runningBalance - $row['due_amount']),
                        'repayment_date' => date('d-m-Y', strtotime($row['due_date']))
                    ];
                    $runningBalance -= $row['due_amount'];
                }
                $scheduleQuery->close();

                $pdfContent = generate_advance_schedule_pdf(
                    $loan_officer_name,
                    $advance_amount,
                    0,
                    0,
                    $payment_date,
                    $scheduleRows
                );
                $subject = 'Advance Payment Applied';
                $body = 'Dear ' . htmlspecialchars($loan_officer_name) . ',<br><br>Your repayment of KES ' . number_format($rep_amount, 2) . ' has been recorded. Your current balance is KES ' . number_format($advance_balance, 2) . '. Please find the updated schedule attached.';
                if (send_pdf_email($loan_officer_email, $subject, $body, $pdfContent, 'advance_payment_update.pdf')) {
                    $messages[] = 'Repayment added and email sent to loan officer.';
                } else {
                    $messages[] = 'Repayment added, but email send failed.';
                }
            } else {
                $messages[] = 'Repayment added; no loan officer email available.';
            }
        } else {
            $messages[] = 'Error adding repayment: ' . $conn->error;
        }
        $stmt->close();
    }

    // Apply monthly deduction
    if (isset($_POST['apply_deduction'])) {
        $advance_id = (int) $_POST['advance_id'];
        $q = $conn->prepare("SELECT monthly_deduction, loan_officer_id, loan_officer_name, amount, balance FROM advances WHERE id = ? LIMIT 1");
        $q->bind_param('i', $advance_id);
        $q->execute();
        $q->bind_result($monthly_deduction, $loan_officer_id, $loan_officer_name, $advance_amount, $advance_balance);
        $q->fetch();
        $q->close();

        if ($monthly_deduction > 0) {
            $payment_date = date('Y-m-d');
            $recorded_by = $_SESSION['user_id'] ?? null;
            $stmt = $conn->prepare("INSERT INTO advance_repayments (advance_id, amount, payment_date, recorded_by) VALUES (?, ?, ?, ?)");
            $stmt->bind_param('idsi', $advance_id, $monthly_deduction, $payment_date, $recorded_by);
            if ($stmt->execute()) {
                $upd = $conn->prepare("UPDATE advances SET balance = balance - ? WHERE id = ?");
                $upd->bind_param('di', $monthly_deduction, $advance_id);
                $upd->execute();
                $upd->close();

                $balanceQuery = $conn->prepare("SELECT a.balance, u.email FROM advances a LEFT JOIN users u ON a.loan_officer_id = u.id WHERE a.id = ? LIMIT 1");
                $balanceQuery->bind_param('i', $advance_id);
                $balanceQuery->execute();
                $balanceQuery->bind_result($advance_balance, $loan_officer_email);
                $balanceQuery->fetch();
                $balanceQuery->close();

                if (!empty($loan_officer_email)) {
                    $scheduleRows = [];
                    $scheduleRows[] = [
                        'amount_due' => $monthly_deduction,
                        'paid' => $monthly_deduction,
                        'balance' => $advance_balance,
                        'repayment_date' => date('d-m-Y', strtotime($payment_date))
                    ];

                    $runningBalance = $advance_balance;
                    $scheduleQuery = $conn->prepare("SELECT due_amount, due_date FROM advance_repayment_schedule WHERE advance_id = ? ORDER BY due_date ASC");
                    $scheduleQuery->bind_param('i', $advance_id);
                    $scheduleQuery->execute();
                    $scheduleResult = $scheduleQuery->get_result();
                    while ($row = $scheduleResult->fetch_assoc()) {
                        $scheduleRows[] = [
                            'amount_due' => $row['due_amount'],
                            'paid' => 0.00,
                            'balance' => max(0, $runningBalance - $row['due_amount']),
                            'repayment_date' => date('d-m-Y', strtotime($row['due_date']))
                        ];
                        $runningBalance -= $row['due_amount'];
                    }
                    $scheduleQuery->close();

                    $pdfContent = generate_advance_schedule_pdf(
                        $loan_officer_name,
                        $advance_amount,
                        0,
                        $monthly_deduction,
                        $payment_date,
                        $scheduleRows
                    );
                    $subject = 'Monthly Advance Deduction Applied';
                    $body = 'Dear ' . htmlspecialchars($loan_officer_name) . ',<br><br>Your monthly deduction of KES ' . number_format($monthly_deduction, 2) . ' has been applied. Your current balance is KES ' . number_format($advance_balance, 2) . '. Please find the updated repayment schedule attached.';
                    if (send_pdf_email($loan_officer_email, $subject, $body, $pdfContent, 'advance_deduction_update.pdf')) {
                        $messages[] = 'Monthly deduction applied and email sent to loan officer.';
                    } else {
                        $messages[] = 'Monthly deduction applied, but email send failed.';
                    }
                } else {
                    $messages[] = 'Monthly deduction applied; no loan officer email available.';
                }
            } else {
                $messages[] = 'Error applying deduction: ' . $conn->error;
            }
            $stmt->close();
        } else {
            $messages[] = 'Monthly deduction is zero for this advance.';
        }
    }

    // Delete templates or advances
    if (isset($_POST['delete_template'])) {
        $tid = (int) $_POST['template_id'];
        $stmt = $conn->prepare("DELETE FROM advance_templates WHERE id = ?");
        $stmt->bind_param('i', $tid);
        if ($stmt->execute()) $messages[] = 'Template deleted.'; else $messages[] = 'Error deleting template: '.$conn->error;
        $stmt->close();
    }
    if (isset($_POST['delete_advance'])) {
        $aid = (int) $_POST['advance_id'];
        $stmt = $conn->prepare("DELETE FROM advance_repayments WHERE advance_id = ?");
        $stmt->bind_param('i', $aid); $stmt->execute(); $stmt->close();
        $stmt = $conn->prepare("DELETE FROM advances WHERE id = ?");
        $stmt->bind_param('i', $aid);
        if ($stmt->execute()) $messages[] = 'Advance deleted.'; else $messages[] = 'Error deleting advance: '.$conn->error;
        $stmt->close();
    }
}

// Fetch data for display
$templates = [];
$tres = $conn->query("SELECT * FROM advance_templates ORDER BY id DESC");
if ($tres) $templates = $tres->fetch_all(MYSQLI_ASSOC);

$advances = [];
$ares = $conn->query("SELECT * FROM advances ORDER BY recorded_at DESC");
if ($ares) $advances = $ares->fetch_all(MYSQLI_ASSOC);

$repayments_map = [];
$rres = $conn->query("SELECT * FROM advance_repayments ORDER BY recorded_at DESC");
if ($rres) {
    while ($r = $rres->fetch_assoc()) {
        $repayments_map[$r['advance_id']][] = $r;
    }
}

$schedule_map = [];
$sres = $conn->query("SELECT * FROM advance_repayment_schedule ORDER BY due_date ASC");
if ($sres) {
    while ($s = $sres->fetch_assoc()) {
        $schedule_map[$s['advance_id']][] = $s;
    }
}

// Fetch loan officers
$loan_officers = [];
$lor = $conn->query("SELECT id, name FROM users WHERE role_id = 2");
if ($lor) {
    while ($row = $lor->fetch_assoc()) $loan_officers[] = $row;
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Advance Management</title>
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="h3 mb-0">Advance Templates & Bookings</h1>
        <a href="./index.php" class="btn btn-secondary btn-sm">Back to Home</a>
    </div>

    <?php foreach ($messages as $m): ?>
        <div class="alert alert-info"><?php echo htmlspecialchars($m); ?></div>
    <?php endforeach; ?>

    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0">Create Advance Template</h5>
                </div>
                <div class="card-body">
                    <form method="POST">
                        <div class="mb-3">
                            <label class="form-label">Template Title</label>
                            <input class="form-control" name="title" placeholder="e.g. loan officer name" required>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Monthly Deduction</label>
                            <input class="form-control" name="monthly_deduction" type="number" step="0.01" value="0.00" required>
                        </div>
                        <button class="btn btn-primary w-100" name="create_template">Save Template</button>
                    </form>
                </div>
            </div>

            <div class="card shadow-sm">
                <div class="card-header bg-secondary text-white">
                    <h5 class="mb-0">Saved Templates</h5>
                </div>
                <div class="card-body p-0">
                    <?php if (count($templates) > 0): ?>
                        <div class="table-responsive">
                            <table class="table table-sm mb-0">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Monthly</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($templates as $t): ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($t['title']); ?></td>
                                            <td><?php echo number_format($t['monthly_deduction'], 2); ?></td>
                                            <td>
                                                <form method="POST" style="display:inline-block; margin:0;">
                                                    <input type="hidden" name="template_id" value="<?php echo $t['id']; ?>">
                                                    <button class="btn btn-sm btn-danger" name="delete_template" onclick="return confirm('Delete template?')">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php else: ?>
                        <div class="p-3 text-muted">No templates defined yet.</div>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card shadow-sm mb-4">
                <div class="card-header bg-success text-white">
                    <h5 class="mb-0">Book Advance to Loan Officer</h5>
                </div>
                <div class="card-body">
                    <form method="POST" class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label">Loan Officer</label>
                            <select id="loan_officer_id" name="loan_officer_id" class="form-select" required>
                                <?php foreach ($loan_officers as $lo): ?>
                                    <option value="<?php echo $lo['id']; ?>"><?php echo htmlspecialchars($lo['name']); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Template (optional)</label>
                            <select name="template_id" id="template_id" class="form-select">
                                <option value="">-- none --</option>
                                <?php foreach ($templates as $t): ?>
                                    <option value="<?php echo $t['id']; ?>" data-monthly="<?php echo $t['monthly_deduction']; ?>"><?php echo htmlspecialchars($t['title']); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Advance Amount</label>
                            <input id="amount" name="amount" class="form-control" type="number" step="0.01" required>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Monthly Deduction</label>
                            <input name="monthly_deduction" id="monthly_deduction" class="form-control" type="number" step="0.01" value="0.00" required>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Duration (months)</label>
                            <input id="duration_months" name="duration_months" class="form-control" type="number" min="1" max="36" value="6" required>
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Start Date</label>
                            <input id="start_date" name="start_date" class="form-control" type="date" value="<?php echo date('Y-m-d'); ?>" required>
                        </div>
                        <input type="hidden" name="edit_advance_id" id="edit_advance_id" value="">
                        <div class="col-12 text-end">
                            <button class="btn btn-success" type="submit" name="book_advance" id="book_advance_btn">Book Advance</button>
                            <button class="btn btn-warning d-none" type="submit" name="update_advance" id="update_advance_btn">Update Advance</button>
                            <button type="button" class="btn btn-secondary d-none" id="cancel_edit_btn" onclick="cancelEdit()">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="card shadow-sm">
                <div class="card-header bg-info text-white">
                    <h5 class="mb-0">Active Advances</h5>
                </div>
                <div class="card-body p-0">
                    <?php if (count($advances) > 0): ?>
                        <div class="table-responsive">
                            <table class="table table-hover mb-0">
                                <thead>
                                    <tr>
                                        <th>Officer</th>
                                        <th>Amount</th>
                                        <th>Balance</th>
                                        <th>Start</th>
                                        <th>Monthly</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($advances as $a): ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($a['loan_officer_name']); ?></td>
                                            <td><?php echo number_format($a['amount'],2); ?></td>
                                            <td><?php echo number_format($a['balance'],2); ?></td>
                                            <td><?php echo date('d-m-Y', strtotime($a['start_date'])); ?></td>
                                            <td><?php echo number_format($a['monthly_deduction'],2); ?></td>
                                            <td>
                                                <form method="POST" style="display:inline-block; margin-right:4px;">
                                                    <input type="hidden" name="advance_id" value="<?php echo $a['id']; ?>">
                                                    <button class="btn btn-sm btn-primary" name="apply_deduction" onclick="return confirm('Apply monthly deduction now?')">Apply Monthly</button>
                                                </form>
                                                <button type="button" class="btn btn-sm btn-secondary" onclick="showRepayForm(<?php echo $a['id']; ?>)">Add Repayment</button>
                                                <button type="button" class="btn btn-sm btn-warning" onclick="editAdvance(<?php echo $a['id']; ?>, <?php echo $a['loan_officer_id']; ?>, '<?php echo !empty($a['template_id']) ? $a['template_id'] : ''; ?>', '<?php echo addslashes($a['amount']); ?>', '<?php echo addslashes($a['monthly_deduction']); ?>', '<?php echo addslashes($a['duration_months'] ?? 1); ?>', '<?php echo $a['start_date']; ?>')">Edit</button>
                                                <button type="button" class="btn btn-sm btn-info" onclick="toggleSchedule(<?php echo $a['id']; ?>)">View Schedule</button>
                                                <form method="POST" style="display:inline-block; margin-left:4px;">
                                                    <input type="hidden" name="advance_id" value="<?php echo $a['id']; ?>">
                                                    <button class="btn btn-sm btn-danger" name="delete_advance" onclick="return confirm('Delete advance? This will remove repayments.')">Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                        <tr id="schedule-row-<?php echo $a['id']; ?>" style="display:none">
                                            <td colspan="6">
                                                <div class="table-responsive">
                                                    <table class="table table-bordered mb-0">
                                                        <thead>
                                                            <tr>
                                                                <th>Amount Due</th>
                                                                <th>Amount Paid</th>
                                                                <th>Repayment Date</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php if (!empty($schedule_map[$a['id']])): ?>
                                                                <?php foreach ($schedule_map[$a['id']] as $schedule): ?>
                                                                    <tr>
                                                                        <td><?php echo number_format($schedule['due_amount'], 2); ?> KES</td>
                                                                        <td>0.00 KES</td>
                                                                        <td><?php echo date('d-m-Y', strtotime($schedule['due_date'])); ?></td>
                                                                    </tr>
                                                                <?php endforeach; ?>
                                                            <?php else: ?>
                                                                <tr><td colspan="3">No schedule generated.</td></tr>
                                                            <?php endif; ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                        <tr id="repay-form-<?php echo $a['id']; ?>" style="display:none">
                                            <td colspan="6">
                                                <form method="POST" class="row g-2">
                                                    <input type="hidden" name="advance_id" value="<?php echo $a['id']; ?>">
                                                    <div class="col-md-4"><input name="repayment_amount" class="form-control" type="number" step="0.01" placeholder="Amount" required></div>
                                                    <div class="col-md-4"><input name="payment_date" class="form-control" type="date" value="<?php echo date('Y-m-d'); ?>" required></div>
                                                    <div class="col-md-4"><button class="btn btn-success" name="add_repayment">Save Repayment</button></div>
                                                </form>
                                                <?php if (!empty($repayments_map[$a['id']])): ?>
                                                    <div class="mt-3">
                                                        <strong>Repayments:</strong>
                                                        <ul class="mb-0">
                                                            <?php foreach ($repayments_map[$a['id']] as $r): ?>
                                                                <li><?php echo date('d-m-Y', strtotime($r['payment_date'])) . ' - ' . number_format($r['amount'],2); ?></li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    </div>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    <?php else: ?>
                        <div class="p-3 text-muted">No advances booked yet.</div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function showRepayForm(id){
    var el = document.getElementById('repay-form-' + id);
    if(el.style.display === 'none') el.style.display = ''; else el.style.display = 'none';
}
function editAdvance(id, loanOfficerId, templateId, amount, monthly, duration, startDate) {
    document.getElementById('edit_advance_id').value = id;
    document.getElementById('loan_officer_id').value = loanOfficerId;
    var templateSelect = document.getElementById('template_id');
    templateSelect.value = templateId || '';
    if (!templateSelect.querySelector('option[value="' + templateSelect.value + '"]')) {
        templateSelect.selectedIndex = 0;
    }
    document.getElementById('amount').value = amount;
    document.getElementById('monthly_deduction').value = monthly;
    document.getElementById('duration_months').value = duration;
    document.getElementById('start_date').value = startDate;
    document.getElementById('book_advance_btn').classList.add('d-none');
    document.getElementById('update_advance_btn').classList.remove('d-none');
    document.getElementById('cancel_edit_btn').classList.remove('d-none');
}
function cancelEdit() {
    document.getElementById('edit_advance_id').value = '';
    document.getElementById('loan_officer_id').selectedIndex = 0;
    document.getElementById('template_id').selectedIndex = 0;
    document.getElementById('amount').value = '';
    document.getElementById('monthly_deduction').value = '0.00';
    document.getElementById('duration_months').value = '6';
    document.getElementById('start_date').value = '<?php echo date('Y-m-d'); ?>';
    document.getElementById('book_advance_btn').classList.remove('d-none');
    document.getElementById('update_advance_btn').classList.add('d-none');
    document.getElementById('cancel_edit_btn').classList.add('d-none');
}
    document.getElementById('template_id').addEventListener('change', function () {
        var selected = this.options[this.selectedIndex];
        var monthly = selected.getAttribute('data-monthly') || '0.00';
        document.getElementById('monthly_deduction').value = parseFloat(monthly).toFixed(2);
    });
function toggleSchedule(id){
    var el = document.getElementById('schedule-row-' + id);
    if (el) {
        el.style.display = (el.style.display === 'none' || el.style.display === '') ? '' : 'none';
    }
}
</script>

</body>
</html>
