<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

session_start();
require_once 'db.php';
require_once __DIR__ . '/../includes/functions.php';

if (empty($_SESSION['email'])) {
    header('Location: ../login.php');
    exit();
}

require_once __DIR__ . '/PHPMailer/src/PHPMailer.php';
require_once __DIR__ . '/PHPMailer/src/Exception.php';
require_once __DIR__ . '/PHPMailer/src/SMTP.php';
require_once __DIR__ . '/TCPDF/tcpdf.php';

function safe($value) {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function buildPayrollSummaryPdf(array $records, $period, $payDate, $analytics = null) {
    $pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
    $pdf->SetCreator('Inua Premium Services');
    $pdf->SetAuthor('Inua Premium Services');
    $pdf->SetTitle('Payroll Summary - ' . $period);
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    $pdf->SetMargins(12, 12, 12);
    $pdf->AddPage();

    $logoPath = __DIR__ . '/../assets/img/logo.png';
    $logoHtml = file_exists($logoPath) ? '<img src="' . $logoPath . '" width="52" />' : '';
    $totalGross = 0;
    $totalDeductions = 0;
    $totalNet = 0;
    $rows = '';
    foreach ($records as $record) {
        $totalGross += (float)$record['gross_pay'];
        $totalDeductions += (float)$record['total_deductions'];
        $totalNet += (float)$record['net_pay'];
        $rows .= '<tr>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['staff_name']) . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['role_name'] ?? $record['staff_role'] ?? '-') . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe(($record['staff_phone'] ?? $record['phone'] ?? '') ?: '-') . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['region_name'] ?: '-') . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['pay_period']) . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['pay_date']) . '</td>
            <td align="right" style="padding:8px;border-bottom:1px solid #dbeafe;">KES ' . number_format((float)$record['gross_pay'], 2) . '</td>
            <td align="right" style="padding:8px;border-bottom:1px solid #dbeafe;">KES ' . number_format((float)$record['total_deductions'], 2) . '</td>
            <td align="right" style="padding:8px;border-bottom:1px solid #dbeafe;font-weight:bold;">KES ' . number_format((float)$record['net_pay'], 2) . '</td>
        </tr>';
    }

    $html = '<table cellpadding="0" cellspacing="0" width="100%">
        <tr><td width="12%">' . $logoHtml . '</td><td width="88%"><h1 style="color:#0f4c81;font-size:22px;margin:0;">Inua Premium Services</h1><p style="color:#64748b;font-size:10px;margin:4px 0;">Payroll Summary Report</p></td></tr>
        <tr><td colspan="2" style="background-color:#0ea5e9;color:#ffffff;padding:12px;font-size:15px;font-weight:bold;">' . safe($period) . ' | Pay date: ' . safe($payDate) . '</td></tr>
        <tr><td colspan="2" style="height:12px;"></td></tr>
        <tr><td colspan="2"><table cellpadding="0" cellspacing="0" width="100%">
            <tr style="background-color:#0f4c81;color:#ffffff;font-weight:bold;"><th width="15%" style="padding:9px;">Staff member</th><th width="12%" style="padding:9px;">Role</th><th width="12%" style="padding:9px;">Phone number</th><th width="13%" style="padding:9px;">Branch</th><th width="13%" style="padding:9px;">Period</th><th width="12%" style="padding:9px;">Pay date</th><th width="11%" align="right" style="padding:9px;">Gross Pay</th><th width="11%" align="right" style="padding:9px;">Advance</th><th width="11%" align="right" style="padding:9px;">Net Pay</th></tr>
            ' . $rows . '
            <tr style="background-color:#e0f2fe;font-weight:bold;"><td colspan="6" style="padding:10px;">TOTAL (' . count($records) . ' staff)</td><td align="right" style="padding:10px;">KES ' . number_format($totalGross, 2) . '</td><td align="right" style="padding:10px;">KES ' . number_format($totalDeductions, 2) . '</td><td align="right" style="padding:10px;">KES ' . number_format($totalNet, 2) . '</td></tr>
        </table></td></tr>
        ' . buildPayrollAnalyticsPdfSection($analytics ?: ['rows' => []]) . '
        <tr><td colspan="2" style="padding-top:18px;color:#64748b;font-size:9px;">Confidential payroll report generated by Inua Premium Services.</td></tr>
    </table>';
    $pdf->writeHTML($html, true, false, true, false, '');
    return $pdf->Output('', 'S');
}

function getPayrollExpenseSummary($conn, $payDate) {
    $periodStart = date('Y-m-01', strtotime($payDate));
    $periodEnd = date('Y-m-t', strtotime($payDate));

    $expenseSummary = ['total' => 0.0, 'rows' => []];
    $stmt = $conn->prepare("SELECT expense_type, COUNT(*) AS entry_count, SUM(amount) AS total_amount FROM loan_officer_expenses WHERE expense_date BETWEEN ? AND ? GROUP BY expense_type ORDER BY total_amount DESC, expense_type ASC");
    if ($stmt) {
        $stmt->bind_param('ss', $periodStart, $periodEnd);
        if ($stmt->execute()) {
            $result = $stmt->get_result();
            while ($row = $result->fetch_assoc()) {
                $amount = (float) ($row['total_amount'] ?? 0);
                $expenseSummary['total'] += $amount;
                $expenseSummary['rows'][] = [
                    'expense_type' => $row['expense_type'] ?? 'Unspecified',
                    'entry_count' => (int) ($row['entry_count'] ?? 0),
                    'total_amount' => $amount,
                ];
            }
        }
        $stmt->close();
    }

    return $expenseSummary;
}

function buildStructuredPayrollSummaryPdf(array $records, $period, $payDate, $analytics = null) {
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
    $pdf->SetCreator('Inua Premium Services');
    $pdf->SetAuthor('Inua Premium Services');
    $pdf->SetTitle('Payroll Summary - ' . $period);
    $pdf->SetMargins(15, 15, 15);
    $pdf->SetAutoPageBreak(false, 15);
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    $safe = function ($value) { return htmlspecialchars(trim((string) $value), ENT_QUOTES, 'UTF-8'); };
    $money = function ($value) { return 'KES ' . number_format((float) $value, 2); };
    $stampPath = __DIR__ . '/New Folder/assets/img/company_stamp.JPG';
    $header = function ($title) use ($pdf, $payDate, $safe) {
        $logoPath = dirname(__DIR__) . '/assets/img/logo.png';
        if (file_exists($logoPath)) {
            $pdf->Image($logoPath, 150, 10, 40, 0, 'PNG');
        }
        $pdf->SetDrawColor(0, 47, 196);
        $pdf->SetLineWidth(1.2);
        $pdf->Line(15, 13, 145, 13);
        $pdf->SetDrawColor(210, 0, 0);
        $pdf->SetLineWidth(0.6);
        $pdf->Line(15, 15, 145, 15);
        $pdf->SetTextColor(0, 47, 196);
        $pdf->SetFont('helvetica', 'B', 18);
        $pdf->Cell(0, 10, 'INUA PREMIUM SERVICES', 0, 1, 'L');
        $pdf->SetTextColor(40, 40, 40);
        $pdf->SetFont('helvetica', '', 9);
        $pdf->Cell(0, 5, 'Human Resources and Payroll Department', 0, 1, 'L');
        $pdf->Cell(0, 5, 'Confidential management document | Pay date: ' . $safe($payDate), 0, 1, 'L');
        $pdf->Ln(4);
        $pdf->SetTextColor(210, 0, 0);
        $pdf->SetFont('helvetica', 'B', 13);
        $pdf->Cell(0, 8, $title, 0, 1, 'C');
        $pdf->SetTextColor(40, 40, 40);
        $pdf->Ln(3);
    };
    $section = function ($title) use ($pdf) {
        $pdf->SetFillColor(11, 47, 159);
        $pdf->SetTextColor(255, 255, 255);
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->Cell(0, 7, $title, 1, 1, 'L', true);
        $pdf->SetTextColor(40, 40, 40);
        $pdf->Ln(2);
    };
    $footer = function ($page) use ($pdf) {
        $pdf->Line(15, 270, 195, 270);
        $pdf->SetFont('helvetica', 'I', 8);
        $pdf->Cell(0, 5, 'Inua Premium Services | Payroll Summary | Page ' . $page, 0, 1, 'C');
    };
    $analyticsRows = $analytics['rows'] ?? [];
    $payrollByStaff = [];
    foreach ($records as $record) {
        $payrollByStaff[(int) $record['staff_id']] = $record;
    }

    $regions = [];
    foreach ($records as $record) {
        $region = trim((string) ($record['region_name'] ?? '')) ?: 'Unassigned Region';
        $regions[$region][] = $record;
    }
    ksort($regions);
    $totalGross = array_sum(array_map('floatval', array_column($records, 'gross_pay')));
    $totalDeductions = array_sum(array_map('floatval', array_column($records, 'total_deductions')));
    $totalNet = array_sum(array_map('floatval', array_column($records, 'net_pay')));
    $expenseSummary = getPayrollExpenseSummary($GLOBALS['conn'], $payDate ?? date('Y-m-d'));
    $totalExpenses = (float) ($expenseSummary['total'] ?? 0);

    $pdf->AddPage();
    $header('PAYROLL SUMMARY REPORT');
    $pdf->SetFont('helvetica', '', 9);
    $pdf->Cell(0, 5, 'Pay period: ' . $safe($period) . ' | Staff records: ' . count($records), 0, 1, 'R');
    $pdf->Ln(2);
    $section('1. PAYROLL CONTROL TOTALS');
    $pdf->writeHTML('<table border="1" cellpadding="4"><tr bgcolor="#e8edff"><td width="35%"><b>Total staff</b></td><td width="65%">' . count($records) . '</td></tr><tr><td><b>Total gross pay</b></td><td>' . $money($totalGross) . '</td></tr><tr><td><b>Total deductions / advances</b></td><td>' . $money($totalDeductions) . '</td></tr><tr><td><b>Total net pay</b></td><td>' . $money($totalNet) . '</td></tr><tr><td><b>Expenses recorded</b></td><td>' . $money($totalExpenses) . '</td></tr></table>', true, false, true, false, 'L');
    $section('2. EXPENSES RECORDED');
    $expenseRows = '';
    foreach (($expenseSummary['rows'] ?? []) as $expense) {
        $expenseRows .= '<tr><td>' . $safe($expense['expense_type']) . '</td><td align="right">' . $safe((string) $expense['entry_count']) . '</td><td align="right">' . $money($expense['total_amount']) . '</td></tr>';
    }
    $pdf->writeHTML('<table border="1" cellpadding="4"><tr bgcolor="#e8edff"><th width="55%"><b>Expense type</b></th><th width="15%"><b>Count</b></th><th width="30%"><b>Recorded amount</b></th></tr>' . ($expenseRows ?: '<tr><td colspan="3">No expense records were captured for this pay period.</td></tr>') . '<tr bgcolor="#f1f5f9"><td><b>TOTAL</b></td><td></td><td align="right"><b>' . $money($totalExpenses) . '</b></td></tr></table>', true, false, true, false, 'L');
    $section('3. PAYROLL BY REGION');
    foreach ($regions as $regionName => $regionRecords) {
        $regionGross = array_sum(array_map('floatval', array_column($regionRecords, 'gross_pay')));
        $regionNet = array_sum(array_map('floatval', array_column($regionRecords, 'net_pay')));
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->Cell(0, 6, 'REGION: ' . $safe($regionName), 0, 1, 'L');
        $rows = '';
        foreach ($regionRecords as $record) {
            $rows .= '<tr><td>' . $safe($record['staff_name']) . '</td><td>' . $safe($record['role_name'] ?? $record['staff_role'] ?? '-') . '</td><td>' . $safe(($record['staff_phone'] ?? $record['phone'] ?? '') ?: '-') . '</td><td>' . $safe($record['pay_period']) . '</td><td align="right">' . $money($record['gross_pay']) . '</td><td align="right">' . $money($record['total_deductions']) . '</td><td align="right">' . $money($record['net_pay']) . '</td></tr>';
        }
        $pdf->writeHTML('<table border="1" cellpadding="3"><tr bgcolor="#e8edff"><th width="22%"><b>Staff member</b></th><th width="12%"><b>Role</b></th><th width="18%"><b>Phone</b></th><th width="15%"><b>Period</b></th><th width="14%"><b>Gross pay</b></th><th width="14%"><b>Deductions</b></th><th width="14%"><b>Net pay</b></th></tr>' . $rows . '<tr bgcolor="#f1f5f9"><td colspan="4"><b>Region total</b></td><td align="right"><b>' . $money($regionGross) . '</b></td><td></td><td align="right"><b>' . $money($regionNet) . '</b></td></tr></table>', true, false, true, false, 'L');
        $pdf->Ln(2);
    }
    $footer(1);

    $pdf->AddPage();
    $header('STAFF PAYROLL AND PERFORMANCE COMPARISON');
    $section('4. STAFF PAYROLL AGAINST KEY PERFORMANCE METRICS');
    $comparisonRows = '';
    foreach ($analyticsRows as $performance) {
        $staffId = (int) ($performance['staff_id'] ?? 0);
        $payroll = $payrollByStaff[$staffId] ?? null;
        if (!$payroll) {
            foreach ($records as $record) {
                if (strcasecmp(trim((string) $record['staff_name']), trim((string) $performance['name'])) === 0) { $payroll = $record; break; }
            }
        }
        $roleName = $payroll['role_name'] ?? $performance['role_name'] ?? ($payroll['staff_role'] ?? '');
        $comparisonRows .= '<tr><td>' . $safe($performance['name']) . '</td><td>' . $safe($roleName ?: '-') . '</td><td>' . $safe($payroll ? (($payroll['staff_phone'] ?? $payroll['phone'] ?? '') ?: '-') : (($performance['phone'] ?? '') ?: '-')) . '</td><td align="right">' . ($payroll ? $money($payroll['gross_pay']) : '-') . '</td><td align="right">' . $money($performance['disbursed']) . '</td><td align="right">' . $money($performance['interest']) . '</td><td align="right">' . $money($performance['repayments']) . '</td><td align="right">' . $money($performance['loanBook']) . '</td></tr>';
    }
    $pdf->writeHTML('<table border="1" cellpadding="3"><tr bgcolor="#e8edff"><th width="18%"><b>Staff member</b></th><th width="12%"><b>Role</b></th><th width="14%"><b>Phone</b></th><th width="12%"><b>Gross pay</b></th><th width="12%"><b>Disbursed</b></th><th width="12%"><b>Interest</b></th><th width="12%"><b>Collected</b></th><th width="12%"><b>Loan book</b></th></tr>' . ($comparisonRows ?: '<tr><td colspan="8">No performance records available.</td></tr>') . '</table>', true, false, true, false, 'L');
    $pdf->Ln(3);
    $pdf->SetFont('helvetica', '', 8.7);
    $pdf->MultiCell(0, 5, 'This comparison places payroll cost beside key role outputs for the corresponding performance period. Management should consider role, portfolio quality, customer service, documentation, arrears, and operational responsibilities before drawing conclusions from financial measures alone.', 0, 'L');
    $section('5. PERFORMANCE REVIEW NOTES');
    $pdf->writeHTML('<table border="1" cellpadding="4"><tr><td width="35%"><b>Review question</b></td><td width="65%"><b>Management discussion</b></td></tr><tr><td>Payroll cost versus output</td><td>Is compensation supported by appropriate disbursement, interest, collections, service, and control performance?</td></tr><tr><td>Underperformance</td><td>Which staff require coaching, a performance plan, workload support, or documented corrective action?</td></tr><tr><td>Data quality</td><td>Are staff assignments, payroll records, advances, collections, and loan performance records complete and current?</td></tr></table>', true, false, true, false, 'L');
    $footer(2);

    $pdf->AddPage();
    $header('ADVANCES ALLOCATED AND MANAGEMENT REVIEW');
    $section('6. ADVANCES ALLOCATED TO STAFF');
    $advanceRows = '';
    $advanceTotals = ['amount' => 0, 'balance' => 0, 'deduction' => 0];
    $advanceResult = $GLOBALS['conn']->query("SELECT a.loan_officer_id, a.loan_officer_name, SUM(a.amount) AS amount, SUM(a.balance) AS balance, SUM(a.monthly_deduction) AS monthly_deduction FROM advances a GROUP BY a.loan_officer_id, a.loan_officer_name ORDER BY a.loan_officer_name ASC");
    if ($advanceResult) {
        while ($advance = $advanceResult->fetch_assoc()) {
            $advanceTotals['amount'] += (float) $advance['amount'];
            $advanceTotals['balance'] += (float) $advance['balance'];
            $advanceTotals['deduction'] += (float) $advance['monthly_deduction'];
            $advanceRows .= '<tr><td>' . $safe($advance['loan_officer_name']) . '</td><td align="right">' . $money($advance['amount']) . '</td><td align="right">' . $money($advance['balance']) . '</td><td align="right">' . $money($advance['monthly_deduction']) . '</td></tr>';
        }
    }
    $pdf->writeHTML('<table border="1" cellpadding="4"><tr bgcolor="#e8edff"><th width="40%"><b>Staff member</b></th><th width="20%"><b>Allocated</b></th><th width="20%"><b>Balance</b></th><th width="20%"><b>Monthly deduction</b></th></tr>' . ($advanceRows ?: '<tr><td colspan="4">No staff advances recorded.</td></tr>') . '<tr bgcolor="#f1f5f9"><td><b>TOTAL</b></td><td align="right"><b>' . $money($advanceTotals['amount']) . '</b></td><td align="right"><b>' . $money($advanceTotals['balance']) . '</b></td><td align="right"><b>' . $money($advanceTotals['deduction']) . '</b></td></tr></table>', true, false, true, false, 'L');
    $section('7. MANAGEMENT ACTIONS');
    $pdf->writeHTML('<table border="1" cellpadding="4"><tr><td width="8%">1</td><td width="92%">Review staff whose advances, deductions, payroll cost, and performance require a documented management discussion.</td></tr><tr><td>2</td><td>Confirm advance balances and deductions are reflected accurately in payroll and staff statements.</td></tr><tr><td>3</td><td>Use the payroll-performance comparison as a review aid, not as the sole basis for disciplinary or remuneration decisions.</td></tr></table>', true, false, true, false, 'L');
    $pdf->Ln(8);
    if (file_exists($stampPath)) {
        $stampY = $pdf->GetY();
        $pdf->SetAlpha(0.42);
        $pdf->Image($stampPath, 146, $stampY - 8, 35, 0, 'JPG', '', '', true, 300, '', false, false, 0, false, false, false);
        $pdf->SetAlpha(1);
    }
    $pdf->SetFont('helvetica', '', 9);
    $pdf->Cell(90, 6, 'Reviewed by: __________________________', 0, 0, 'L');
    $pdf->Cell(0, 6, 'Date: ____/____/________', 0, 1, 'L');
    $pdf->Ln(8);
    $pdf->Cell(90, 6, 'Manager signature: _____________________', 0, 0, 'L');
    $pdf->Cell(0, 6, 'Next review: ____/____/________', 0, 1, 'L');
    $footer(3);
    return $pdf->Output('', 'S');
}

function getPayrollStaffAnalytics($conn, $payDate) {
    $monthStart = date('Y-m-01', strtotime($payDate));
    $monthEnd = date('Y-m-d', strtotime($payDate));
    $staff = [];
    $staffResult = $conn->query("SELECT u.id, u.name, u.email, u.phone, COALESCE(r.name, 'Unassigned Role') AS role_name, COALESCE(ar.area_name, 'Unassigned Region') AS region_name
                                FROM users u LEFT JOIN roles r ON r.id = u.role_id LEFT JOIN areas ar ON ar.area_id = u.area
                                WHERE u.role_id = 2 ORDER BY u.name ASC");
    if (!$staffResult) {
        return ['monthStart' => $monthStart, 'monthEnd' => $monthEnd, 'rows' => []];
    }

    while ($officer = $staffResult->fetch_assoc()) {
        $email = $officer['email'];
        $loanStmt = $conn->prepare("SELECT
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN la.principal ELSE 0 END), 0) AS disbursed,
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN GREATEST(la.total_amount - la.principal, 0) ELSE 0 END), 0) AS interest_generated,
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN la.processing_fee ELSE 0 END), 0) AS processing_fee,
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN la.registration_fee ELSE 0 END), 0) AS registration_fee,
                COALESCE(SUM(CASE WHEN la.loan_release_date <= ? AND la.loan_status = 'approved' THEN GREATEST(la.total_amount - COALESCE((SELECT SUM(COALESCE(r2.paid, 0)) FROM repayments r2 WHERE r2.loan_id = la.id AND r2.repayment_date <= ?), 0), 0) ELSE 0 END), 0) AS loan_book
            FROM borrowers b
            INNER JOIN loan_applications la ON la.borrower = b.id
            WHERE b.loan_officer = ?");
        $loanStmt->bind_param('sssssssssss', $monthStart, $monthEnd, $monthStart, $monthEnd, $monthStart, $monthEnd, $monthStart, $monthEnd, $monthEnd, $monthEnd, $email);
        $loanStmt->execute();
        $loanMetrics = $loanStmt->get_result()->fetch_assoc() ?: [];
        $loanStmt->close();

        $repaymentStmt = $conn->prepare("SELECT COALESCE(SUM(CASE WHEN r.repaid_date BETWEEN ? AND ? THEN COALESCE(r.paid, 0) WHEN r.repaid_date IS NULL AND r.repayment_date BETWEEN ? AND ? THEN COALESCE(r.paid, 0) ELSE 0 END), 0) AS repayments_collected
            FROM repayments r
            INNER JOIN loan_applications la ON la.id = r.loan_id
            INNER JOIN borrowers b ON b.id = la.borrower
            WHERE b.loan_officer = ?");
        $repaymentStmt->bind_param('sssss', $monthStart, $monthEnd, $monthStart, $monthEnd, $email);
        $repaymentStmt->execute();
        $repaymentMetrics = $repaymentStmt->get_result()->fetch_assoc() ?: [];
        $repaymentStmt->close();

        $interest = (float)($loanMetrics['interest_generated'] ?? 0);
        $processingFee = (float)($loanMetrics['processing_fee'] ?? 0);
        $registrationFee = (float)($loanMetrics['registration_fee'] ?? 0);
        $fees = $processingFee + $registrationFee;
        $staff[] = [
            'staff_id' => (int) $officer['id'],
            'name' => $officer['name'],
            'phone' => $officer['phone'] ?? '',
            'region_name' => $officer['region_name'],
            'phone' => '',
            'disbursed' => (float)($loanMetrics['disbursed'] ?? 0),
            'interest' => $interest,
            'loanBook' => (float)($loanMetrics['loan_book'] ?? 0),
            'processingFee' => $processingFee,
            'registrationFee' => $registrationFee,
            'fees' => $fees,
            'netIncome' => $interest + $fees,
            'repayments' => (float)($repaymentMetrics['repayments_collected'] ?? 0),
        ];
    }

    return ['monthStart' => $monthStart, 'monthEnd' => $monthEnd, 'rows' => $staff];
}

function buildPayrollAnalyticsPdfSection($analytics) {
    if (empty($analytics['rows'])) {
        return '<tr><td colspan="2" style="padding-top:18px;color:#64748b;font-size:10px;">No loan officer analytics were available for this month.</td></tr>';
    }

    $totals = ['disbursed' => 0, 'interest' => 0, 'loanBook' => 0, 'fees' => 0, 'netIncome' => 0, 'repayments' => 0];
    $rows = '';
    foreach ($analytics['rows'] as $row) {
        foreach ($totals as $key => $value) {
            $totals[$key] += $row[$key];
        }
        $rows .= '<tr>
            <td style="padding:7px;border-bottom:1px solid #dbeafe;">' . safe($row['name']) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['disbursed'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['interest'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['loanBook'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['processingFee'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['registrationFee'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['fees'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;font-weight:bold;">KES ' . number_format($row['netIncome'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['repayments'], 2) . '</td>
        </tr>';
    }

    $maxValue = max(1, max(array_column($analytics['rows'], 'netIncome')));
    $chartRows = '';
    foreach ($analytics['rows'] as $row) {
        $width = max(2, min(100, ($row['netIncome'] / $maxValue) * 100));
        $chartRows .= '<tr><td width="24%" style="padding:4px;font-size:9px;">' . safe($row['name']) . '</td><td style="padding:4px;"><table cellpadding="0" cellspacing="0" width="100%"><tr><td width="' . $width . '%" style="height:12px;background-color:#0ea5e9;"></td><td></td></tr></table></td><td width="16%" align="right" style="padding:4px;font-size:9px;">KES ' . number_format($row['netIncome'], 0) . '</td></tr>';
    }

    return '<tr><td colspan="2" style="padding-top:24px;"><h2 style="color:#0f4c81;font-size:17px;margin:0 0 4px;">Staff Portfolio Analytics</h2><p style="color:#64748b;font-size:9px;margin:0 0 12px;">Performance period: ' . safe(date('d F Y', strtotime($analytics['monthStart']))) . ' to ' . safe(date('d F Y', strtotime($analytics['monthEnd']))) . '. Manager and administrator accounts are excluded. Disbursements, interest, and fees are recognized for loans released within this period. Loan book is measured as of the pay date, while collections reflect cash recorded during this period.</p>
        <table cellpadding="0" cellspacing="0" width="100%"><tr style="background-color:#0f4c81;color:#ffffff;font-weight:bold;"><th width="16%" style="padding:8px;">Staff member</th><th width="11%" align="right" style="padding:8px;">Disbursed</th><th width="11%" align="right" style="padding:8px;">Interest</th><th width="11%" align="right" style="padding:8px;">Loan book</th><th width="11%" align="right" style="padding:8px;">Processing fee</th><th width="11%" align="right" style="padding:8px;">Registration fee</th><th width="11%" align="right" style="padding:8px;">Total fees</th><th width="10%" align="right" style="padding:8px;">Net income</th><th width="9%" align="right" style="padding:8px;">Collected</th></tr>' . $rows . '<tr style="background-color:#e0f2fe;font-weight:bold;"><td style="padding:8px;">TOTAL</td><td align="right" style="padding:8px;">KES ' . number_format($totals['disbursed'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['interest'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['loanBook'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format(array_sum(array_column($analytics['rows'], 'processingFee')), 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format(array_sum(array_column($analytics['rows'], 'registrationFee')), 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['fees'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['netIncome'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['repayments'], 2) . '</td></tr></table>
        <h3 style="color:#0f4c81;font-size:13px;margin:18px 0 6px;">Net income by loan officer</h3><table cellpadding="0" cellspacing="0" width="100%">' . $chartRows . '</table>
    </td></tr>';
}

$conn->query("CREATE TABLE IF NOT EXISTS payroll_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$conn->query("CREATE TABLE IF NOT EXISTS staff_payrolls (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_id INT DEFAULT NULL,
    template_name VARCHAR(150) DEFAULT NULL,
    staff_id INT NOT NULL,
    staff_name VARCHAR(150) NOT NULL,
    staff_email VARCHAR(150) DEFAULT NULL,
    pay_period VARCHAR(100) NOT NULL,
    pay_date DATE NOT NULL,
    basic_salary DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    gross_pay DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_deductions DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    net_pay DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    earnings LONGTEXT,
    deductions LONGTEXT,
    notes TEXT DEFAULT NULL,
    recorded_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_staff_id (staff_id),
    KEY idx_pay_period (pay_period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$columnCheck = $conn->query("SHOW COLUMNS FROM staff_payrolls LIKE 'region_id'");
if ($columnCheck && $columnCheck->num_rows === 0) {
    $conn->query("ALTER TABLE staff_payrolls ADD COLUMN region_id INT DEFAULT NULL, ADD COLUMN region_name VARCHAR(150) DEFAULT NULL");
}

$regions = [];
$regionsResult = $conn->query("SELECT area_id, area_name FROM areas ORDER BY area_name ASC");
if ($regionsResult) {
    while ($row = $regionsResult->fetch_assoc()) {
        $regions[] = $row;
    }
}

$selectedRegionId = isset($_GET['region_id']) ? (int)$_GET['region_id'] : 0;
$selectedRegionName = '';
if ($selectedRegionId > 0) {
    foreach ($regions as $region) {
        if ((int)$region['area_id'] === $selectedRegionId) {
            $selectedRegionName = $region['area_name'];
            break;
        }
    }
}

$message = '';
$error = '';
$queuedPayrollId = 0;
$queuedPayrollPeriod = '';
if (!empty($_SESSION['payroll_email_queue']['ids']) && is_array($_SESSION['payroll_email_queue']['ids'])) {
    $queuedPayrollId = (int) array_shift($_SESSION['payroll_email_queue']['ids']);
    $queuedPayrollPeriod = (string) ($_SESSION['payroll_email_queue']['period'] ?? '');
    if (empty($_SESSION['payroll_email_queue']['ids'])) {
        unset($_SESSION['payroll_email_queue']);
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' || $queuedPayrollId > 0) {
    if (isset($_POST['clear_id'])) {
        $clearId = (int)$_POST['clear_id'];
        if ($clearId > 0) {
            $stmt = $conn->prepare("DELETE FROM staff_payrolls WHERE id = ? LIMIT 1");
            $stmt->bind_param('i', $clearId);
            if ($stmt->execute()) {
                $message = 'Payroll record cleared successfully.';
            } else {
                $error = 'Unable to clear payroll record. Please try again.';
            }
            $stmt->close();
        }
    }

    if (isset($_POST['send_mail_id']) || $queuedPayrollId > 0) {
        $sendMailId = $queuedPayrollId > 0 ? $queuedPayrollId : (int)$_POST['send_mail_id'];
        if ($sendMailId > 0) {
            $payrollStmt = $conn->prepare("SELECT sp.*, u.email AS user_email, u.phone AS staff_phone,
                    COALESCE((SELECT SUM(a.balance) FROM advances a WHERE a.loan_officer_id = sp.staff_id AND a.balance > 0), 0) AS current_advance_balance
                FROM staff_payrolls sp
                LEFT JOIN users u ON sp.staff_id = u.id
                WHERE sp.id = ? LIMIT 1");
            $payrollStmt->bind_param('i', $sendMailId);
            $payrollStmt->execute();
            $payrollResult = $payrollStmt->get_result();
            $payroll = $payrollResult ? $payrollResult->fetch_assoc() : null;
            $payrollStmt->close();

            if (!$payroll) {
                $error = 'Payroll record not found.';
            } else {
                $emailRecipient = !empty($payroll['user_email']) ? $payroll['user_email'] : $payroll['staff_email'];
                if (empty($emailRecipient)) {
                    $error = 'Staff email address is not available.';
                } else {
                    $emailCredentials = getPayrollEmailAccount();
                    if (empty($emailCredentials['sender_email']) || empty($emailCredentials['sender_app_password'])) {
                        $error = 'Manager payroll email settings are not configured. Please configure the manager sender email and app password in Payroll Settings.';
                    } else {
                        $logoPath = __DIR__ . '/../assets/img/logo.png';
                        $mail = new PHPMailer(true);
                        try {
                            $mail->SMTPOptions = [
                                'ssl' => [
                                    'verify_peer' => false,
                                    'verify_peer_name' => false,
                                    'allow_self_signed' => true,
                                ],
                            ];
                            $mail->SMTPDebug = 0;
                            $mail->CharSet = 'UTF-8';
                            $mail->isSMTP();
                            $smtpSettings = getPayrollSmtpSettings($emailCredentials['sender_email']);
                            $mail->Host = $smtpSettings['host'];
                            $mail->SMTPAuth = true;
                            $mail->Username = $emailCredentials['sender_email'];
                            $mail->Password = $emailCredentials['sender_app_password'];
                            $mail->SMTPSecure = $smtpSettings['encryption'];
                            $mail->SMTPAutoTLS = true;
                            $mail->Port = $smtpSettings['port'];
                            $mail->setFrom($emailCredentials['sender_email'], 'Inua Premium Services');
                            $mail->addReplyTo($emailCredentials['sender_email'], 'Inua Premium Services');
                            $mail->addAddress($emailRecipient, $payroll['staff_name']);
                            $mail->isHTML(true);
                            $mail->Subject = 'Payslip Document for ' . ($payroll['pay_period'] ?: 'this period');
                        if (file_exists($logoPath)) {
                            $mail->addEmbeddedImage($logoPath, 'company_logo');
                        }
                        $body = '<html><body style="margin:0;padding:0;font-family:Inter,Arial,sans-serif;background:#eaf5ff;color:#0f172a;">';
                        $body .= '<table width="100%" cellpadding="0" cellspacing="0" style="background:#eaf5ff;padding:24px;">';
                        $body .= '<tr><td align="center">';
                        $body .= '<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:24px;overflow:hidden;box-shadow:0 28px 80px rgba(14,88,161,0.15);border:1px solid #dbeafe;">';
                        $body .= '<tr><td style="padding:28px 32px;background:#0ea5e9;color:#ffffff;text-align:center;">';
                        if (file_exists($logoPath)) {
                            $body .= '<img src="cid:company_logo" alt="Company Logo" width="96" style="display:block;margin:0 auto 18px;">';
                        }
                        $body .= '<h1 style="margin:0;font-size:28px;font-weight:700;letter-spacing:-0.04em;">Inua Premium Services</h1>';
                        $body .= '<p style="margin:10px 0 0;font-size:15px;color:#dbeafe;">Payslip Document • ' . safe($payroll['pay_period']) . '</p>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:0 32px 16px;">';
                        $body .= '<p style="margin:0;font-size:14px;color:#e0f2fe;">Official payroll document for the period, issued for staff records and verification.</p>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:28px 32px 16px;">';
                        $body .= '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">';
                        $body .= '<tr>';
                        $body .= '<td width="52%" valign="top" style="padding-right:16px;">';
                        $body .= '<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:16px;padding:18px;">';
                        $body .= '<p style="margin:0 0 10px;font-size:13px;color:#1d4ed8;font-weight:700;letter-spacing:0.03em;text-transform:uppercase;">Employee</p>';
                        $body .= '<p style="margin:0;font-size:16px;font-weight:600;color:#111827;">' . safe($payroll['staff_name']) . '</p>';
                        $body .= '<p style="margin:8px 0 0;font-size:14px;color:#475569;">' . safe($emailRecipient) . '</p>';
                        $body .= '<p style="margin:8px 0 0;font-size:14px;color:#475569;">' . safe($payroll['staff_phone'] ?: '-') . '</p>';
                        $body .= '</div>';
                        $body .= '</td>';
                        $body .= '<td width="48%" valign="top" style="padding-left:16px;">';
                        $body .= '<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:16px;padding:18px;">';
                        $body .= '<p style="margin:0 0 10px;font-size:13px;color:#1d4ed8;font-weight:700;letter-spacing:0.03em;text-transform:uppercase;">Payslip Details</p>';
                        $body .= '<p style="margin:0;font-size:14px;color:#111827;"><strong>Period:</strong> ' . safe($payroll['pay_period']) . '</p>';
                        $body .= '<p style="margin:10px 0 0;font-size:14px;color:#111827;"><strong>Pay date:</strong> ' . safe($payroll['pay_date']) . '</p>';
                        $body .= '<p style="margin:10px 0 0;font-size:14px;color:#111827;"><strong>Region:</strong> ' . safe($payroll['region_name'] ?: '-') . '</p>';
                        $body .= '<p style="margin:10px 0 0;font-size:14px;color:#111827;"><strong>Advance balance:</strong> KES ' . number_format((float)$payroll['current_advance_balance'], 2) . '</p>';
                        $body .= '</div>';
                        $body .= '</td>';
                        $body .= '</tr>';
                        $body .= '</table>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding-bottom:4px;">';
                        $body .= '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden;background:#ffffff;">';
                        $body .= '<tr style="background:#0ea5e9;color:#ffffff;"><th align="left" style="padding:18px 20px;font-size:14px;letter-spacing:0.02em;">Earnings & Deductions</th><th align="right" style="padding:18px 20px;font-size:14px;letter-spacing:0.02em;">Amount</th></tr>';
                        $body .= '<tr><td style="padding:16px 20px;font-size:14px;color:#475569;">Basic salary</td><td align="right" style="padding:16px 20px;font-size:14px;color:#111827;">KES ' . number_format((float)$payroll['basic_salary'], 2) . '</td></tr>';
                        $body .= '<tr><td style="padding:16px 20px;font-size:14px;color:#475569;">Gross pay</td><td align="right" style="padding:16px 20px;font-size:14px;color:#111827;">KES ' . number_format((float)$payroll['gross_pay'], 2) . '</td></tr>';
                        $body .= '<tr><td style="padding:16px 20px;font-size:14px;color:#475569;">Total deductions</td><td align="right" style="padding:16px 20px;font-size:14px;color:#111827;">KES ' . number_format((float)$payroll['total_deductions'], 2) . '</td></tr>';
                        $body .= '<tr style="background:#bae6fd;"><td style="padding:16px 20px;font-size:16px;font-weight:700;color:#0f172a;">Net pay</td><td align="right" style="padding:16px 20px;font-size:16px;font-weight:700;color:#0f172a;">KES ' . number_format((float)$payroll['net_pay'], 2) . '</td></tr>';
                        $body .= '</table>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:0 0 26px;">';
                        $body .= '<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:18px;padding:20px;">';
                        $body .= '<p style="margin:0;font-size:13px;color:#475569;line-height:1.7;">This payslip document is an official payroll record for the current period. Keep it for your records and present it as needed for verification.</p>';
                        $body .= '</div>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:0 0 28px;">';
                        $body .= '<p style="margin:0;font-size:13px;color:#94a3b8;text-align:center;">Inua Premium Services — Trusted payroll for staff and operations.</p>';
                        $body .= '</td></tr>';
                        $body .= '</table>';
                        $body .= '</td></tr></table>';
                        $body .= '</td></tr></table>';
                        $body .= '</body></html>';
                        $mail->Body = $body;
                        $mail->AltBody = "Payslip Document for {$payroll['pay_period']}\nEmployee: {$payroll['staff_name']}\nGross pay: KES " . number_format((float)$payroll['gross_pay'], 2) . "\nTotal deductions: KES " . number_format((float)$payroll['total_deductions'], 2) . "\nNet pay: KES " . number_format((float)$payroll['net_pay'], 2) . "\nCurrent advance balance: KES " . number_format((float)$payroll['current_advance_balance'], 2) . "\n\nThis document is issued for payroll record and verification purposes.";
                        $mail->send();
                        $message = 'Payslip document sent successfully to ' . safe($emailRecipient) . '.';
                    } catch (Exception $e) {
                        $error = 'Unable to send payslip email: ' . $mail->ErrorInfo;
                    }
                }
            }
        }
    }
}
}

if (!empty($_SESSION['payroll_email_queue']['ids'])) {
    header('Location: view_payroll.php');
    exit();
}

if ($queuedPayrollId > 0 && $queuedPayrollPeriod !== '' && empty($_SESSION['payroll_email_queue'])) {
    $summaryStmt = $conn->prepare("SELECT sp.*, u.email AS staff_email, u.phone AS staff_phone, COALESCE(r.name, 'Unassigned Role') AS role_name FROM staff_payrolls sp LEFT JOIN users u ON sp.staff_id = u.id LEFT JOIN roles r ON r.id = u.role_id WHERE sp.pay_period = ? ORDER BY sp.staff_name ASC");
    $summaryStmt->bind_param('s', $queuedPayrollPeriod);
    $summaryStmt->execute();
    $summaryResult = $summaryStmt->get_result();
    $summaryRecords = $summaryResult ? $summaryResult->fetch_all(MYSQLI_ASSOC) : [];
    $summaryStmt->close();

    if (!empty($summaryRecords)) {
        $managerCredentials = getPayrollEmailAccount();
        $managerEmail = $managerCredentials['sender_email'] ?? '';
        if ($managerEmail !== '' && !empty($managerCredentials['sender_app_password'])) {
            try {
                $payrollAnalytics = getPayrollStaffAnalytics($conn, $summaryRecords[0]['pay_date']);
                $summaryMail = new PHPMailer(true);
                $summaryMail->SMTPOptions = ['ssl' => ['verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true]];
                $summaryMail->SMTPDebug = 0;
                $summaryMail->CharSet = 'UTF-8';
                $summaryMail->isSMTP();
                $smtpSettings = getPayrollSmtpSettings($managerEmail);
                $summaryMail->Host = $smtpSettings['host'];
                $summaryMail->SMTPAuth = true;
                $summaryMail->Username = $managerEmail;
                $summaryMail->Password = $managerCredentials['sender_app_password'];
                $summaryMail->SMTPSecure = $smtpSettings['encryption'];
                $summaryMail->SMTPAutoTLS = true;
                $summaryMail->Port = $smtpSettings['port'];
                $summaryMail->setFrom($managerEmail, 'Inua Premium Services Payroll');
                $summaryMail->addAddress($managerEmail, 'Payroll Manager');
                $summaryMail->Subject = 'Payroll Summary - ' . $queuedPayrollPeriod;
                $summaryMail->isHTML(true);
                $summaryMail->Body = '<p>Attached is the payroll summary for <strong>' . safe($queuedPayrollPeriod) . '</strong>.</p><p>This report contains the payroll records sent to staff.</p>';
                $summaryMail->AltBody = 'Attached is the payroll summary for ' . $queuedPayrollPeriod . '.';
                $summaryMail->addStringAttachment(buildStructuredPayrollSummaryPdf($summaryRecords, $queuedPayrollPeriod, $summaryRecords[0]['pay_date'], $payrollAnalytics), 'payroll-summary-' . preg_replace('/[^A-Za-z0-9_-]/', '-', $queuedPayrollPeriod) . '.pdf', 'base64', 'application/pdf');
                $summaryMail->send();
                $message = 'Payroll payslips sent to staff and summary report emailed to the manager.';
            } catch (Exception $e) {
                $error = 'Payslips were sent, but the manager summary email failed: ' . $summaryMail->ErrorInfo;
            }
        } else {
            $error = 'Payslips were sent, but the manager summary was not emailed because Payroll Settings credentials are missing.';
        }
    }
}

$recentPayrolls = [];
$selectedPeriod = trim((string)($_GET['pay_period'] ?? ''));
$periodOptions = [];
$periodResult = $conn->query("SELECT pay_period, MAX(pay_date) AS latest_pay_date FROM staff_payrolls WHERE pay_period IS NOT NULL AND pay_period <> '' GROUP BY pay_period ORDER BY latest_pay_date DESC, pay_period DESC");
if ($periodResult) {
    while ($periodRow = $periodResult->fetch_assoc()) {
        $periodOptions[] = $periodRow['pay_period'];
    }
}

$sql = "SELECT sp.id, sp.staff_name, sp.staff_id, u.phone AS staff_phone, u.email AS staff_email, COALESCE(r.name, 'Unassigned Role') AS role_name, sp.region_name, sp.pay_period, sp.pay_date, sp.gross_pay, sp.total_deductions, sp.net_pay, sp.created_at FROM staff_payrolls sp LEFT JOIN users u ON sp.staff_id = u.id LEFT JOIN roles r ON r.id = u.role_id";
$conditions = [];
$queryParams = [];
$queryTypes = '';
if ($selectedRegionId > 0) {
    $conditions[] = 'sp.region_id = ?';
    $queryParams[] = $selectedRegionId;
    $queryTypes .= 'i';
}
if ($selectedPeriod !== '') {
    $conditions[] = 'sp.pay_period = ?';
    $queryParams[] = $selectedPeriod;
    $queryTypes .= 's';
}
if (!empty($conditions)) {
    $sql .= ' WHERE ' . implode(' AND ', $conditions);
}
$sql .= " ORDER BY sp.created_at DESC";
$recentStmt = $conn->prepare($sql);
if (!empty($queryParams)) {
    $recentStmt->bind_param($queryTypes, ...$queryParams);
}
$recentStmt->execute();
$recentResult = $recentStmt->get_result();
if ($recentResult) {
    $recentPayrolls = $recentResult->fetch_all(MYSQLI_ASSOC);
}
$summaryStaff = count($recentPayrolls);
$summaryGross = array_sum(array_column($recentPayrolls, 'gross_pay'));
$summaryAdvance = array_sum(array_column($recentPayrolls, 'total_deductions'));
$summaryNet = array_sum(array_column($recentPayrolls, 'net_pay'));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Payroll Records</title>
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root { --ink:#172331; --muted:#687582; --line:#dbe3e8; --paper:#fff; --canvas:#f2f5f6; --teal:#147d78; --gold:#c7973e; }
        body { background:var(--canvas); color:var(--ink); font-family:"Trebuchet MS",Arial,sans-serif; }
        .report-shell { max-width:1280px; margin:34px auto 60px; padding:0 22px; }
        .report-heading { background:var(--ink); border-top:4px solid var(--gold); color:#fff; padding:30px 34px 27px; position:relative; }
        .report-heading h1 { font-family:Georgia,serif; font-size:clamp(1.8rem,3vw,2.6rem); font-weight:normal; letter-spacing:.02em; margin:0 0 8px; }
        .report-heading p { color:#c3d0d6; margin:0; }
        .report-meta { color:#e5c579; font-size:.8rem; letter-spacing:.12em; text-transform:uppercase; }
        .report-actions { position:absolute; right:34px; bottom:27px; display:flex; gap:8px; }
        .report-actions a { border:1px solid #82939c; color:#fff; background:transparent; padding:8px 14px; text-decoration:none; }
        .report-actions a:hover { background:var(--teal); border-color:var(--teal); }
        .metric-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; margin:18px 0; }
        .metric { background:var(--paper); border:1px solid var(--line); border-left:4px solid var(--teal); padding:18px 20px; }
        .metric:nth-child(2){border-left-color:var(--gold)} .metric:nth-child(3){border-left-color:#5b7180} .metric:nth-child(4){border-left-color:#a95d55}
        .metric-label { color:var(--muted); font-size:.74rem; letter-spacing:.1em; text-transform:uppercase; }
        .metric-value { display:block; font-family:Georgia,serif; font-size:1.45rem; margin-top:8px; }
        .table-panel { background:var(--paper); border:1px solid var(--line); }
        .panel-heading { border-bottom:1px solid var(--line); padding:18px 22px; }
        .panel-heading h2 { font-family:Georgia,serif; font-size:1.25rem; margin:0; }
        .panel-heading span { color:var(--muted); font-size:.85rem; }
        .report-table { margin:0; }
        .report-table thead th { background:#edf2f3; border-bottom:2px solid var(--teal); color:#425460; font-size:.72rem; letter-spacing:.08em; padding:14px 18px; text-transform:uppercase; white-space:nowrap; }
        .report-table tbody td { border-color:#e6ecef; padding:15px 18px; vertical-align:middle; }
        .report-table tbody tr:hover { background:#f7faf9; }
        .summary-title { font-family:Georgia,serif; font-size:1.25rem; margin:0; }
        .summary-metrics { display:grid; grid-template-columns:repeat(4,1fr); gap:14px; padding:18px 22px; }
        .summary-metric { background:#f7faf9; border:1px solid var(--line); padding:16px; }
        .summary-metric small { color:var(--muted); text-transform:uppercase; letter-spacing:.08em; }
        .summary-metric h3 { font-family:Georgia,serif; margin:8px 0 0; }
        .report-footer { color:var(--muted); font-size:.78rem; margin-top:14px; }
        @media(max-width:850px){.report-heading{padding:24px}.report-actions{margin-top:20px;position:static}.metric-grid,.summary-metrics{grid-template-columns:repeat(2,1fr)}}
        @media(max-width:520px){.report-shell{padding:0 12px}.metric-grid,.summary-metrics{grid-template-columns:1fr}.report-heading h1{font-size:1.8rem}}
        @media print{body{background:#fff}.report-shell{margin:0;max-width:none}.report-actions,#header{display:none!important}.report-heading{color:#000;background:#fff;border:1px solid #999}.report-heading p,.report-meta{color:#444}.metric,.table-panel{break-inside:avoid}}
    </style>
</head>
<body>
<main class="report-shell" id="mainContent">
    <section class="report-heading">
        <div>
            <div class="report-meta">Management report · Payroll register</div>
            <h1>Payroll Records</h1>
            <p>Review recent payroll entries and monitor gross pay, deductions, and net pay for staff.</p>
        </div>
        <div class="report-actions">
            <a href="index.php">Back to Dashboard</a>
            <a href="add_payroll.php">Add payroll</a>
        </div>
    </section>

    <section class="table-panel" style="margin-top:18px;">
        <div class="panel-heading d-flex justify-content-between align-items-center gap-3">
            <h2>Payroll register</h2><span><?php echo count($recentPayrolls); ?> records · Prepared <?php echo date('d F Y'); ?></span>
        </div>
        <form method="GET" action="view_payroll.php" class="row g-3 align-items-end mb-3">
            <div class="col-lg-4">
                <label class="form-label" for="region_id">Filter by region</label>
                <select id="region_id" name="region_id" class="form-select">
                    <option value="0">All regions</option>
                    <?php foreach ($regions as $region): ?>
                        <option value="<?php echo (int)$region['area_id']; ?>"<?php echo $selectedRegionId === (int)$region['area_id'] ? ' selected' : ''; ?>>
                            <?php echo safe($region['area_name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-lg-4">
                <label class="form-label" for="pay_period">Filter by period</label>
                <select id="pay_period" name="pay_period" class="form-select">
                    <option value="">All periods</option>
                    <?php foreach ($periodOptions as $periodOption): ?>
                        <option value="<?php echo safe($periodOption); ?>"<?php echo $selectedPeriod === $periodOption ? ' selected' : ''; ?>>
                            <?php echo safe($periodOption); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-lg-2">
                <button type="submit" class="btn btn-primary">Apply filter</button>
            </div>
        </form>
        <?php if ($message): ?>
            <div class="alert alert-success"><?php echo safe($message); ?></div>
        <?php endif; ?>
        <?php if ($error): ?>
            <div class="alert alert-danger"><?php echo safe($error); ?></div>
        <?php endif; ?>
        <?php if (empty($recentPayrolls)): ?>
            <p class="text-muted">No payroll records found yet.</p>
        <?php else: ?>
            <div class="table-responsive">
                <table class="table report-table align-middle">
                    <thead>
                        <tr>
                            <th>Staff</th>
                            <th>Role</th>
                            <th>Phone number</th>
                            <th>Branch</th>
                            <th>Period</th>
                            <th>Pay date</th>
                            <th class="text-end">Gross Pay</th>
                            <th class="text-end">Advance</th>
                            <th class="text-end">Net Pay</th>
                            <th>Saved</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($recentPayrolls as $row): ?>
                            <tr>
                                <td><?php echo safe($row['staff_name']); ?></td>
                                <td><?php echo safe($row['role_name'] ?? '-'); ?></td>
                                <td><?php echo safe($row['staff_phone'] ?: '-'); ?></td>
                                <td><?php echo safe($row['region_name'] ?: '-'); ?></td>
                                <td><?php echo safe($row['pay_period']); ?></td>
                                <td><?php echo safe($row['pay_date']); ?></td>
                                <td class="text-end">KES <?php echo number_format((float)$row['gross_pay'], 2); ?></td>
                                <td class="text-end">KES <?php echo number_format((float)$row['total_deductions'], 2); ?></td>
                                <td class="text-end">KES <?php echo number_format((float)$row['net_pay'], 2); ?></td>
                                <td><?php echo safe($row['created_at']); ?></td>
                                <td>
                                    <div class="d-flex gap-2">
                                        <form method="POST" action="view_payroll.php" onsubmit="return confirm('Clear this payroll record?');">
                                            <input type="hidden" name="clear_id" value="<?php echo (int)$row['id']; ?>">
                                            <button type="submit" class="btn btn-sm btn-outline-danger">Clear</button>
                                        </form>
                                        <form method="POST" action="view_payroll.php">
                                            <input type="hidden" name="send_mail_id" value="<?php echo (int)$row['id']; ?>">
                                            <button type="submit" class="btn btn-sm btn-outline-primary">Send Mail</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>

        <div class="panel-heading" style="border-top:1px solid var(--line);"><h2 class="summary-title">Payroll Summary<?php echo $selectedPeriod !== '' ? ' · ' . safe($selectedPeriod) : ''; ?></h2></div>
        <div class="summary-metrics">
            <div class="summary-metric"><small>Total staff</small><h3><?php echo number_format($summaryStaff); ?></h3></div>
            <div class="summary-metric"><small>Total gross pay</small><h3>KES <?php echo number_format((float)$summaryGross, 2); ?></h3></div>
            <div class="summary-metric"><small>Total advance</small><h3>KES <?php echo number_format((float)$summaryAdvance, 2); ?></h3></div>
            <div class="summary-metric"><small>Total net pay</small><h3>KES <?php echo number_format((float)$summaryNet, 2); ?></h3></div>
        </div>
    </section>
    <div class="report-footer">Source: staff payroll register · All amounts are presented in Kenyan Shillings (KES).</div>
</main>
</body>
</html>
