<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

session_start();
require_once 'db.php';
require_once __DIR__ . '/../includes/functions.php';

if (empty($_SESSION['email'])) {
    header('Location: ../login.php');
    exit();
}

require_once __DIR__ . '/PHPMailer/src/PHPMailer.php';
require_once __DIR__ . '/PHPMailer/src/Exception.php';
require_once __DIR__ . '/PHPMailer/src/SMTP.php';
require_once __DIR__ . '/TCPDF/tcpdf.php';

function safe($value) {
    return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
}

function buildPayrollSummaryPdf(array $records, $period, $payDate, $analytics = null) {
    $pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
    $pdf->SetCreator('Inua Premium Services');
    $pdf->SetAuthor('Inua Premium Services');
    $pdf->SetTitle('Payroll Summary - ' . $period);
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    $pdf->SetMargins(12, 12, 12);
    $pdf->AddPage();

    $logoPath = __DIR__ . '/../assets/img/logo.png';
    $logoHtml = file_exists($logoPath) ? '<img src="' . $logoPath . '" width="52" />' : '';
    $totalGross = 0;
    $totalDeductions = 0;
    $totalNet = 0;
    $rows = '';
    foreach ($records as $record) {
        $totalGross += (float)$record['gross_pay'];
        $totalDeductions += (float)$record['total_deductions'];
        $totalNet += (float)$record['net_pay'];
        $rows .= '<tr>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['staff_name']) . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe(($record['staff_phone'] ?? $record['phone'] ?? '') ?: '-') . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['region_name'] ?: '-') . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['pay_period']) . '</td>
            <td style="padding:8px;border-bottom:1px solid #dbeafe;">' . safe($record['pay_date']) . '</td>
            <td align="right" style="padding:8px;border-bottom:1px solid #dbeafe;">KES ' . number_format((float)$record['gross_pay'], 2) . '</td>
            <td align="right" style="padding:8px;border-bottom:1px solid #dbeafe;">KES ' . number_format((float)$record['total_deductions'], 2) . '</td>
            <td align="right" style="padding:8px;border-bottom:1px solid #dbeafe;font-weight:bold;">KES ' . number_format((float)$record['net_pay'], 2) . '</td>
        </tr>';
    }

    $html = '<table cellpadding="0" cellspacing="0" width="100%">
        <tr><td width="12%">' . $logoHtml . '</td><td width="88%"><h1 style="color:#0f4c81;font-size:22px;margin:0;">Inua Premium Services</h1><p style="color:#64748b;font-size:10px;margin:4px 0;">Payroll Summary Report</p></td></tr>
        <tr><td colspan="2" style="background-color:#0ea5e9;color:#ffffff;padding:12px;font-size:15px;font-weight:bold;">' . safe($period) . ' | Pay date: ' . safe($payDate) . '</td></tr>
        <tr><td colspan="2" style="height:12px;"></td></tr>
        <tr><td colspan="2"><table cellpadding="0" cellspacing="0" width="100%">
            <tr style="background-color:#0f4c81;color:#ffffff;font-weight:bold;"><th width="17%" style="padding:9px;">Staff member</th><th width="12%" style="padding:9px;">Phone number</th><th width="13%" style="padding:9px;">Branch</th><th width="13%" style="padding:9px;">Period</th><th width="12%" style="padding:9px;">Pay date</th><th width="11%" align="right" style="padding:9px;">Gross Pay</th><th width="11%" align="right" style="padding:9px;">Advance</th><th width="11%" align="right" style="padding:9px;">Net Pay</th></tr>
            ' . $rows . '
            <tr style="background-color:#e0f2fe;font-weight:bold;"><td colspan="5" style="padding:10px;">TOTAL (' . count($records) . ' staff)</td><td align="right" style="padding:10px;">KES ' . number_format($totalGross, 2) . '</td><td align="right" style="padding:10px;">KES ' . number_format($totalDeductions, 2) . '</td><td align="right" style="padding:10px;">KES ' . number_format($totalNet, 2) . '</td></tr>
        </table></td></tr>
        ' . buildPayrollAnalyticsPdfSection($analytics ?: ['rows' => []]) . '
        <tr><td colspan="2" style="padding-top:18px;color:#64748b;font-size:9px;">Confidential payroll report generated by Inua Premium Services.</td></tr>
    </table>';
    $pdf->writeHTML($html, true, false, true, false, '');
    return $pdf->Output('', 'S');
}

function getPayrollStaffAnalytics($conn, $payDate) {
    $monthStart = date('Y-m-01', strtotime($payDate));
    $monthEnd = date('Y-m-d', strtotime($payDate));
    $staff = [];
    $staffResult = $conn->query("SELECT id, name, email FROM users WHERE role_id = 2 ORDER BY name ASC");
    if (!$staffResult) {
        return ['monthStart' => $monthStart, 'monthEnd' => $monthEnd, 'rows' => []];
    }

    while ($officer = $staffResult->fetch_assoc()) {
        $email = $officer['email'];
        $loanStmt = $conn->prepare("SELECT
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN la.principal ELSE 0 END), 0) AS disbursed,
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN GREATEST(la.total_amount - la.principal, 0) ELSE 0 END), 0) AS interest_generated,
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN la.processing_fee ELSE 0 END), 0) AS processing_fee,
                COALESCE(SUM(CASE WHEN la.loan_release_date BETWEEN ? AND ? AND la.loan_status = 'approved' THEN la.registration_fee ELSE 0 END), 0) AS registration_fee,
                COALESCE(SUM(CASE WHEN la.loan_release_date <= ? AND la.loan_status = 'approved' THEN GREATEST(la.total_amount - COALESCE((SELECT SUM(COALESCE(r2.paid, 0)) FROM repayments r2 WHERE r2.loan_id = la.id AND r2.repayment_date <= ?), 0), 0) ELSE 0 END), 0) AS loan_book
            FROM borrowers b
            INNER JOIN loan_applications la ON la.borrower = b.id
            WHERE b.loan_officer = ?");
        $loanStmt->bind_param('sssssssssss', $monthStart, $monthEnd, $monthStart, $monthEnd, $monthStart, $monthEnd, $monthStart, $monthEnd, $monthEnd, $monthEnd, $email);
        $loanStmt->execute();
        $loanMetrics = $loanStmt->get_result()->fetch_assoc() ?: [];
        $loanStmt->close();

        $repaymentStmt = $conn->prepare("SELECT COALESCE(SUM(CASE WHEN r.repaid_date BETWEEN ? AND ? THEN COALESCE(r.paid, 0) WHEN r.repaid_date IS NULL AND r.repayment_date BETWEEN ? AND ? THEN COALESCE(r.paid, 0) ELSE 0 END), 0) AS repayments_collected
            FROM repayments r
            INNER JOIN loan_applications la ON la.id = r.loan_id
            INNER JOIN borrowers b ON b.id = la.borrower
            WHERE b.loan_officer = ?");
        $repaymentStmt->bind_param('sssss', $monthStart, $monthEnd, $monthStart, $monthEnd, $email);
        $repaymentStmt->execute();
        $repaymentMetrics = $repaymentStmt->get_result()->fetch_assoc() ?: [];
        $repaymentStmt->close();

        $interest = (float)($loanMetrics['interest_generated'] ?? 0);
        $processingFee = (float)($loanMetrics['processing_fee'] ?? 0);
        $registrationFee = (float)($loanMetrics['registration_fee'] ?? 0);
        $fees = $processingFee + $registrationFee;
        $staff[] = [
            'name' => $officer['name'],
            'phone' => '',
            'disbursed' => (float)($loanMetrics['disbursed'] ?? 0),
            'interest' => $interest,
            'loanBook' => (float)($loanMetrics['loan_book'] ?? 0),
            'processingFee' => $processingFee,
            'registrationFee' => $registrationFee,
            'fees' => $fees,
            'netIncome' => $interest + $fees,
            'repayments' => (float)($repaymentMetrics['repayments_collected'] ?? 0),
        ];
    }

    return ['monthStart' => $monthStart, 'monthEnd' => $monthEnd, 'rows' => $staff];
}

function buildPayrollAnalyticsPdfSection($analytics) {
    if (empty($analytics['rows'])) {
        return '<tr><td colspan="2" style="padding-top:18px;color:#64748b;font-size:10px;">No loan officer analytics were available for this month.</td></tr>';
    }

    $totals = ['disbursed' => 0, 'interest' => 0, 'loanBook' => 0, 'fees' => 0, 'netIncome' => 0, 'repayments' => 0];
    $rows = '';
    foreach ($analytics['rows'] as $row) {
        foreach ($totals as $key => $value) {
            $totals[$key] += $row[$key];
        }
        $rows .= '<tr>
            <td style="padding:7px;border-bottom:1px solid #dbeafe;">' . safe($row['name']) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['disbursed'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['interest'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['loanBook'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['processingFee'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['registrationFee'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['fees'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;font-weight:bold;">KES ' . number_format($row['netIncome'], 2) . '</td>
            <td align="right" style="padding:7px;border-bottom:1px solid #dbeafe;">KES ' . number_format($row['repayments'], 2) . '</td>
        </tr>';
    }

    $maxValue = max(1, max(array_column($analytics['rows'], 'netIncome')));
    $chartRows = '';
    foreach ($analytics['rows'] as $row) {
        $width = max(2, min(100, ($row['netIncome'] / $maxValue) * 100));
        $chartRows .= '<tr><td width="24%" style="padding:4px;font-size:9px;">' . safe($row['name']) . '</td><td style="padding:4px;"><table cellpadding="0" cellspacing="0" width="100%"><tr><td width="' . $width . '%" style="height:12px;background-color:#0ea5e9;"></td><td></td></tr></table></td><td width="16%" align="right" style="padding:4px;font-size:9px;">KES ' . number_format($row['netIncome'], 0) . '</td></tr>';
    }

    return '<tr><td colspan="2" style="padding-top:24px;"><h2 style="color:#0f4c81;font-size:17px;margin:0 0 4px;">Staff Portfolio Analytics</h2><p style="color:#64748b;font-size:9px;margin:0 0 12px;">Performance period: ' . safe(date('d F Y', strtotime($analytics['monthStart']))) . ' to ' . safe(date('d F Y', strtotime($analytics['monthEnd']))) . '. Manager and administrator accounts are excluded. Disbursements, interest, and fees are recognized for loans released within this period. Loan book is measured as of the pay date, while collections reflect cash recorded during this period.</p>
        <table cellpadding="0" cellspacing="0" width="100%"><tr style="background-color:#0f4c81;color:#ffffff;font-weight:bold;"><th width="16%" style="padding:8px;">Staff member</th><th width="11%" align="right" style="padding:8px;">Disbursed</th><th width="11%" align="right" style="padding:8px;">Interest</th><th width="11%" align="right" style="padding:8px;">Loan book</th><th width="11%" align="right" style="padding:8px;">Processing fee</th><th width="11%" align="right" style="padding:8px;">Registration fee</th><th width="11%" align="right" style="padding:8px;">Total fees</th><th width="10%" align="right" style="padding:8px;">Net income</th><th width="9%" align="right" style="padding:8px;">Collected</th></tr>' . $rows . '<tr style="background-color:#e0f2fe;font-weight:bold;"><td style="padding:8px;">TOTAL</td><td align="right" style="padding:8px;">KES ' . number_format($totals['disbursed'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['interest'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['loanBook'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format(array_sum(array_column($analytics['rows'], 'processingFee')), 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format(array_sum(array_column($analytics['rows'], 'registrationFee')), 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['fees'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['netIncome'], 2) . '</td><td align="right" style="padding:8px;">KES ' . number_format($totals['repayments'], 2) . '</td></tr></table>
        <h3 style="color:#0f4c81;font-size:13px;margin:18px 0 6px;">Net income by loan officer</h3><table cellpadding="0" cellspacing="0" width="100%">' . $chartRows . '</table>
    </td></tr>';
}

$conn->query("CREATE TABLE IF NOT EXISTS payroll_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT DEFAULT NULL,
    created_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$conn->query("CREATE TABLE IF NOT EXISTS staff_payrolls (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_id INT DEFAULT NULL,
    template_name VARCHAR(150) DEFAULT NULL,
    staff_id INT NOT NULL,
    staff_name VARCHAR(150) NOT NULL,
    staff_email VARCHAR(150) DEFAULT NULL,
    pay_period VARCHAR(100) NOT NULL,
    pay_date DATE NOT NULL,
    basic_salary DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    gross_pay DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_deductions DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    net_pay DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    earnings LONGTEXT,
    deductions LONGTEXT,
    notes TEXT DEFAULT NULL,
    recorded_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_staff_id (staff_id),
    KEY idx_pay_period (pay_period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");

$columnCheck = $conn->query("SHOW COLUMNS FROM staff_payrolls LIKE 'region_id'");
if ($columnCheck && $columnCheck->num_rows === 0) {
    $conn->query("ALTER TABLE staff_payrolls ADD COLUMN region_id INT DEFAULT NULL, ADD COLUMN region_name VARCHAR(150) DEFAULT NULL");
}

$regions = [];
$regionsResult = $conn->query("SELECT area_id, area_name FROM areas ORDER BY area_name ASC");
if ($regionsResult) {
    while ($row = $regionsResult->fetch_assoc()) {
        $regions[] = $row;
    }
}

$selectedRegionId = isset($_GET['region_id']) ? (int)$_GET['region_id'] : 0;
$selectedRegionName = '';
if ($selectedRegionId > 0) {
    foreach ($regions as $region) {
        if ((int)$region['area_id'] === $selectedRegionId) {
            $selectedRegionName = $region['area_name'];
            break;
        }
    }
}

$message = '';
$error = '';
$queuedPayrollId = 0;
$queuedPayrollPeriod = '';
if (!empty($_SESSION['payroll_email_queue']['ids']) && is_array($_SESSION['payroll_email_queue']['ids'])) {
    $queuedPayrollId = (int) array_shift($_SESSION['payroll_email_queue']['ids']);
    $queuedPayrollPeriod = (string) ($_SESSION['payroll_email_queue']['period'] ?? '');
    if (empty($_SESSION['payroll_email_queue']['ids'])) {
        unset($_SESSION['payroll_email_queue']);
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' || $queuedPayrollId > 0) {
    if (isset($_POST['clear_id'])) {
        $clearId = (int)$_POST['clear_id'];
        if ($clearId > 0) {
            $stmt = $conn->prepare("DELETE FROM staff_payrolls WHERE id = ? LIMIT 1");
            $stmt->bind_param('i', $clearId);
            if ($stmt->execute()) {
                $message = 'Payroll record cleared successfully.';
            } else {
                $error = 'Unable to clear payroll record. Please try again.';
            }
            $stmt->close();
        }
    }

    if (isset($_POST['send_mail_id']) || $queuedPayrollId > 0) {
        $sendMailId = $queuedPayrollId > 0 ? $queuedPayrollId : (int)$_POST['send_mail_id'];
        if ($sendMailId > 0) {
            $payrollStmt = $conn->prepare("SELECT sp.*, u.email AS user_email, u.phone AS staff_phone FROM staff_payrolls sp LEFT JOIN users u ON sp.staff_id = u.id WHERE sp.id = ? LIMIT 1");
            $payrollStmt->bind_param('i', $sendMailId);
            $payrollStmt->execute();
            $payrollResult = $payrollStmt->get_result();
            $payroll = $payrollResult ? $payrollResult->fetch_assoc() : null;
            $payrollStmt->close();

            if (!$payroll) {
                $error = 'Payroll record not found.';
            } else {
                $emailRecipient = !empty($payroll['user_email']) ? $payroll['user_email'] : $payroll['staff_email'];
                if (empty($emailRecipient)) {
                    $error = 'Staff email address is not available.';
                } else {
                    $emailCredentials = getPayrollEmailAccount();
                    if (empty($emailCredentials['sender_email']) || empty($emailCredentials['sender_app_password'])) {
                        $error = 'Manager payroll email settings are not configured. Please configure the manager sender email and app password in Payroll Settings.';
                    } else {
                        $logoPath = __DIR__ . '/../assets/img/logo.png';
                        $mail = new PHPMailer(true);
                        try {
                            $mail->SMTPOptions = [
                                'ssl' => [
                                    'verify_peer' => false,
                                    'verify_peer_name' => false,
                                    'allow_self_signed' => true,
                                ],
                            ];
                            $mail->SMTPDebug = 0;
                            $mail->CharSet = 'UTF-8';
                            $mail->isSMTP();
                            $smtpSettings = getPayrollSmtpSettings($emailCredentials['sender_email']);
                            $mail->Host = $smtpSettings['host'];
                            $mail->SMTPAuth = true;
                            $mail->Username = $emailCredentials['sender_email'];
                            $mail->Password = $emailCredentials['sender_app_password'];
                            $mail->SMTPSecure = $smtpSettings['encryption'];
                            $mail->SMTPAutoTLS = true;
                            $mail->Port = $smtpSettings['port'];
                            $mail->setFrom($emailCredentials['sender_email'], 'Inua Premium Services');
                            $mail->addReplyTo($emailCredentials['sender_email'], 'Inua Premium Services');
                            $mail->addAddress($emailRecipient, $payroll['staff_name']);
                            $mail->isHTML(true);
                            $mail->Subject = 'Payslip Document for ' . ($payroll['pay_period'] ?: 'this period');
                        if (file_exists($logoPath)) {
                            $mail->addEmbeddedImage($logoPath, 'company_logo');
                        }
                        $body = '<html><body style="margin:0;padding:0;font-family:Inter,Arial,sans-serif;background:#eaf5ff;color:#0f172a;">';
                        $body .= '<table width="100%" cellpadding="0" cellspacing="0" style="background:#eaf5ff;padding:24px;">';
                        $body .= '<tr><td align="center">';
                        $body .= '<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:24px;overflow:hidden;box-shadow:0 28px 80px rgba(14,88,161,0.15);border:1px solid #dbeafe;">';
                        $body .= '<tr><td style="padding:28px 32px;background:#0ea5e9;color:#ffffff;text-align:center;">';
                        if (file_exists($logoPath)) {
                            $body .= '<img src="cid:company_logo" alt="Company Logo" width="96" style="display:block;margin:0 auto 18px;">';
                        }
                        $body .= '<h1 style="margin:0;font-size:28px;font-weight:700;letter-spacing:-0.04em;">Inua Premium Services</h1>';
                        $body .= '<p style="margin:10px 0 0;font-size:15px;color:#dbeafe;">Payslip Document • ' . safe($payroll['pay_period']) . '</p>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:0 32px 16px;">';
                        $body .= '<p style="margin:0;font-size:14px;color:#e0f2fe;">Official payroll document for the period, issued for staff records and verification.</p>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:28px 32px 16px;">';
                        $body .= '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">';
                        $body .= '<tr>';
                        $body .= '<td width="52%" valign="top" style="padding-right:16px;">';
                        $body .= '<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:16px;padding:18px;">';
                        $body .= '<p style="margin:0 0 10px;font-size:13px;color:#1d4ed8;font-weight:700;letter-spacing:0.03em;text-transform:uppercase;">Employee</p>';
                        $body .= '<p style="margin:0;font-size:16px;font-weight:600;color:#111827;">' . safe($payroll['staff_name']) . '</p>';
                        $body .= '<p style="margin:8px 0 0;font-size:14px;color:#475569;">' . safe($emailRecipient) . '</p>';
                        $body .= '<p style="margin:8px 0 0;font-size:14px;color:#475569;">' . safe($payroll['staff_phone'] ?: '-') . '</p>';
                        $body .= '</div>';
                        $body .= '</td>';
                        $body .= '<td width="48%" valign="top" style="padding-left:16px;">';
                        $body .= '<div style="background:#eff6ff;border:1px solid #bfdbfe;border-radius:16px;padding:18px;">';
                        $body .= '<p style="margin:0 0 10px;font-size:13px;color:#1d4ed8;font-weight:700;letter-spacing:0.03em;text-transform:uppercase;">Payslip Details</p>';
                        $body .= '<p style="margin:0;font-size:14px;color:#111827;"><strong>Period:</strong> ' . safe($payroll['pay_period']) . '</p>';
                        $body .= '<p style="margin:10px 0 0;font-size:14px;color:#111827;"><strong>Pay date:</strong> ' . safe($payroll['pay_date']) . '</p>';
                        $body .= '<p style="margin:10px 0 0;font-size:14px;color:#111827;"><strong>Region:</strong> ' . safe($payroll['region_name'] ?: '-') . '</p>';
                        $body .= '</div>';
                        $body .= '</td>';
                        $body .= '</tr>';
                        $body .= '</table>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding-bottom:4px;">';
                        $body .= '<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden;background:#ffffff;">';
                        $body .= '<tr style="background:#0ea5e9;color:#ffffff;"><th align="left" style="padding:18px 20px;font-size:14px;letter-spacing:0.02em;">Earnings & Deductions</th><th align="right" style="padding:18px 20px;font-size:14px;letter-spacing:0.02em;">Amount</th></tr>';
                        $body .= '<tr><td style="padding:16px 20px;font-size:14px;color:#475569;">Basic salary</td><td align="right" style="padding:16px 20px;font-size:14px;color:#111827;">KES ' . number_format((float)$payroll['basic_salary'], 2) . '</td></tr>';
                        $body .= '<tr><td style="padding:16px 20px;font-size:14px;color:#475569;">Gross pay</td><td align="right" style="padding:16px 20px;font-size:14px;color:#111827;">KES ' . number_format((float)$payroll['gross_pay'], 2) . '</td></tr>';
                        $body .= '<tr><td style="padding:16px 20px;font-size:14px;color:#475569;">Total deductions</td><td align="right" style="padding:16px 20px;font-size:14px;color:#111827;">KES ' . number_format((float)$payroll['total_deductions'], 2) . '</td></tr>';
                        $body .= '<tr style="background:#bae6fd;"><td style="padding:16px 20px;font-size:16px;font-weight:700;color:#0f172a;">Net pay</td><td align="right" style="padding:16px 20px;font-size:16px;font-weight:700;color:#0f172a;">KES ' . number_format((float)$payroll['net_pay'], 2) . '</td></tr>';
                        $body .= '</table>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:0 0 26px;">';
                        $body .= '<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:18px;padding:20px;">';
                        $body .= '<p style="margin:0;font-size:13px;color:#475569;line-height:1.7;">This payslip document is an official payroll record for the current period. Keep it for your records and present it as needed for verification.</p>';
                        $body .= '</div>';
                        $body .= '</td></tr>';
                        $body .= '<tr><td style="padding:0 0 28px;">';
                        $body .= '<p style="margin:0;font-size:13px;color:#94a3b8;text-align:center;">Inua Premium Services — Trusted payroll for staff and operations.</p>';
                        $body .= '</td></tr>';
                        $body .= '</table>';
                        $body .= '</td></tr></table>';
                        $body .= '</td></tr></table>';
                        $body .= '</body></html>';
                        $mail->Body = $body;
                        $mail->AltBody = "Payslip Document for {$payroll['pay_period']}\nEmployee: {$payroll['staff_name']}\nGross pay: KES " . number_format((float)$payroll['gross_pay'], 2) . "\nTotal deductions: KES " . number_format((float)$payroll['total_deductions'], 2) . "\nNet pay: KES " . number_format((float)$payroll['net_pay'], 2) . "\n\nThis document is issued for payroll record and verification purposes.";
                        $mail->send();
                        $message = 'Payslip document sent successfully to ' . safe($emailRecipient) . '.';
                    } catch (Exception $e) {
                        $error = 'Unable to send payslip email: ' . $mail->ErrorInfo;
                    }
                }
            }
        }
    }
}
}

if (!empty($_SESSION['payroll_email_queue']['ids'])) {
    header('Location: view_payroll.php');
    exit();
}

if ($queuedPayrollId > 0 && $queuedPayrollPeriod !== '' && empty($_SESSION['payroll_email_queue'])) {
    $summaryStmt = $conn->prepare("SELECT sp.*, u.email AS staff_email, u.phone AS staff_phone FROM staff_payrolls sp LEFT JOIN users u ON sp.staff_id = u.id WHERE sp.pay_period = ? ORDER BY sp.staff_name ASC");
    $summaryStmt->bind_param('s', $queuedPayrollPeriod);
    $summaryStmt->execute();
    $summaryResult = $summaryStmt->get_result();
    $summaryRecords = $summaryResult ? $summaryResult->fetch_all(MYSQLI_ASSOC) : [];
    $summaryStmt->close();

    if (!empty($summaryRecords)) {
        $managerCredentials = getPayrollEmailAccount();
        $managerEmail = $managerCredentials['sender_email'] ?? '';
        if ($managerEmail !== '' && !empty($managerCredentials['sender_app_password'])) {
            try {
                $payrollAnalytics = getPayrollStaffAnalytics($conn, $summaryRecords[0]['pay_date']);
                $summaryMail = new PHPMailer(true);
                $summaryMail->SMTPOptions = ['ssl' => ['verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true]];
                $summaryMail->SMTPDebug = 0;
                $summaryMail->CharSet = 'UTF-8';
                $summaryMail->isSMTP();
                $smtpSettings = getPayrollSmtpSettings($managerEmail);
                $summaryMail->Host = $smtpSettings['host'];
                $summaryMail->SMTPAuth = true;
                $summaryMail->Username = $managerEmail;
                $summaryMail->Password = $managerCredentials['sender_app_password'];
                $summaryMail->SMTPSecure = $smtpSettings['encryption'];
                $summaryMail->SMTPAutoTLS = true;
                $summaryMail->Port = $smtpSettings['port'];
                $summaryMail->setFrom($managerEmail, 'Inua Premium Services Payroll');
                $summaryMail->addAddress($managerEmail, 'Payroll Manager');
                $summaryMail->Subject = 'Payroll Summary - ' . $queuedPayrollPeriod;
                $summaryMail->isHTML(true);
                $summaryMail->Body = '<p>Attached is the payroll summary for <strong>' . safe($queuedPayrollPeriod) . '</strong>.</p><p>This report contains the payroll records sent to staff.</p>';
                $summaryMail->AltBody = 'Attached is the payroll summary for ' . $queuedPayrollPeriod . '.';
                $summaryMail->addStringAttachment(buildPayrollSummaryPdf($summaryRecords, $queuedPayrollPeriod, $summaryRecords[0]['pay_date'], $payrollAnalytics), 'payroll-summary-' . preg_replace('/[^A-Za-z0-9_-]/', '-', $queuedPayrollPeriod) . '.pdf', 'base64', 'application/pdf');
                $summaryMail->send();
                $message = 'Payroll payslips sent to staff and summary report emailed to the manager.';
            } catch (Exception $e) {
                $error = 'Payslips were sent, but the manager summary email failed: ' . $summaryMail->ErrorInfo;
            }
        } else {
            $error = 'Payslips were sent, but the manager summary was not emailed because Payroll Settings credentials are missing.';
        }
    }
}

$recentPayrolls = [];
$selectedPeriod = trim((string)($_GET['pay_period'] ?? ''));
$periodOptions = [];
$periodResult = $conn->query("SELECT pay_period, MAX(pay_date) AS latest_pay_date FROM staff_payrolls WHERE pay_period IS NOT NULL AND pay_period <> '' GROUP BY pay_period ORDER BY latest_pay_date DESC, pay_period DESC");
if ($periodResult) {
    while ($periodRow = $periodResult->fetch_assoc()) {
        $periodOptions[] = $periodRow['pay_period'];
    }
}

$sql = "SELECT sp.id, sp.staff_name, sp.staff_id, u.phone AS staff_phone, u.email AS staff_email, sp.region_name, sp.pay_period, sp.pay_date, sp.gross_pay, sp.total_deductions, sp.net_pay, sp.created_at FROM staff_payrolls sp LEFT JOIN users u ON sp.staff_id = u.id";
$conditions = [];
$queryParams = [];
$queryTypes = '';
if ($selectedRegionId > 0) {
    $conditions[] = 'sp.region_id = ?';
    $queryParams[] = $selectedRegionId;
    $queryTypes .= 'i';
}
if ($selectedPeriod !== '') {
    $conditions[] = 'sp.pay_period = ?';
    $queryParams[] = $selectedPeriod;
    $queryTypes .= 's';
}
if (!empty($conditions)) {
    $sql .= ' WHERE ' . implode(' AND ', $conditions);
}
$sql .= " ORDER BY sp.created_at DESC";
$recentStmt = $conn->prepare($sql);
if (!empty($queryParams)) {
    $recentStmt->bind_param($queryTypes, ...$queryParams);
}
$recentStmt->execute();
$recentResult = $recentStmt->get_result();
if ($recentResult) {
    $recentPayrolls = $recentResult->fetch_all(MYSQLI_ASSOC);
}
$summaryStaff = count($recentPayrolls);
$summaryGross = array_sum(array_column($recentPayrolls, 'gross_pay'));
$summaryAdvance = array_sum(array_column($recentPayrolls, 'total_deductions'));
$summaryNet = array_sum(array_column($recentPayrolls, 'net_pay'));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Payroll Records</title>
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background: #eef2ff; color: #0f172a; font-family: 'Inter', sans-serif; }
        .container { max-width: 1140px; margin: 24px auto; padding: 0 18px 32px; }
        .card { border-radius: 24px; background: #fff; box-shadow: 0 24px 60px rgba(15, 23, 42, 0.08); border: 1px solid rgba(148, 163, 184, 0.16); padding: 28px; }
        .hero { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 20px; }
        .hero h1 { margin: 0; font-size: 2.3rem; letter-spacing: -0.04em; }
        .summary-title { font-size: 1.1rem; font-weight: 700; margin-bottom: 18px; }
        .badge-soft { display: inline-flex; align-items: center; gap: 6px; padding: 8px 12px; border-radius: 999px; background: #eef2ff; color: #4338ca; font-size: 0.95rem; }
    </style>
</head>
<body>
<div class="container">
    <div class="card hero">
        <div>
            <h1>Payroll Records</h1>
            <p>Review recent payroll entries and monitor gross pay, deductions, and net pay for staff.</p>
        </div>
        <div class="d-flex align-items-center gap-3">
            <a href="index.php" class="btn btn-outline-primary">Back to Dashboard</a>
            <div class="badge-soft"><?php echo count($recentPayrolls); ?> records</div>
        </div>
    </div>

    <div class="card mt-4">
        <form method="GET" action="view_payroll.php" class="row g-3 align-items-end mb-3">
            <div class="col-lg-4">
                <label class="form-label" for="region_id">Filter by region</label>
                <select id="region_id" name="region_id" class="form-select">
                    <option value="0">All regions</option>
                    <?php foreach ($regions as $region): ?>
                        <option value="<?php echo (int)$region['area_id']; ?>"<?php echo $selectedRegionId === (int)$region['area_id'] ? ' selected' : ''; ?>>
                            <?php echo safe($region['area_name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-lg-4">
                <label class="form-label" for="pay_period">Filter by period</label>
                <select id="pay_period" name="pay_period" class="form-select">
                    <option value="">All periods</option>
                    <?php foreach ($periodOptions as $periodOption): ?>
                        <option value="<?php echo safe($periodOption); ?>"<?php echo $selectedPeriod === $periodOption ? ' selected' : ''; ?>>
                            <?php echo safe($periodOption); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-lg-2">
                <button type="submit" class="btn btn-primary">Apply filter</button>
            </div>
        </form>
        <?php if ($message): ?>
            <div class="alert alert-success"><?php echo safe($message); ?></div>
        <?php endif; ?>
        <?php if ($error): ?>
            <div class="alert alert-danger"><?php echo safe($error); ?></div>
        <?php endif; ?>
        <?php if (empty($recentPayrolls)): ?>
            <p class="text-muted">No payroll records found yet.</p>
        <?php else: ?>
            <div class="table-responsive">
                <table class="table table-striped align-middle">
                    <thead>
                        <tr>
                            <th>Staff</th>
                            <th>Phone number</th>
                            <th>Branch</th>
                            <th>Period</th>
                            <th>Pay date</th>
                            <th class="text-end">Gross Pay</th>
                            <th class="text-end">Advance</th>
                            <th class="text-end">Net Pay</th>
                            <th>Saved</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($recentPayrolls as $row): ?>
                            <tr>
                                <td><?php echo safe($row['staff_name']); ?></td>
                                <td><?php echo safe($row['staff_phone'] ?: '-'); ?></td>
                                <td><?php echo safe($row['region_name'] ?: '-'); ?></td>
                                <td><?php echo safe($row['pay_period']); ?></td>
                                <td><?php echo safe($row['pay_date']); ?></td>
                                <td class="text-end">KES <?php echo number_format((float)$row['gross_pay'], 2); ?></td>
                                <td class="text-end">KES <?php echo number_format((float)$row['total_deductions'], 2); ?></td>
                                <td class="text-end">KES <?php echo number_format((float)$row['net_pay'], 2); ?></td>
                                <td><?php echo safe($row['created_at']); ?></td>
                                <td>
                                    <div class="d-flex gap-2">
                                        <form method="POST" action="view_payroll.php" onsubmit="return confirm('Clear this payroll record?');">
                                            <input type="hidden" name="clear_id" value="<?php echo (int)$row['id']; ?>">
                                            <button type="submit" class="btn btn-sm btn-outline-danger">Clear</button>
                                        </form>
                                        <form method="POST" action="view_payroll.php">
                                            <input type="hidden" name="send_mail_id" value="<?php echo (int)$row['id']; ?>">
                                            <button type="submit" class="btn btn-sm btn-outline-primary">Send Mail</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>

        <div class="mt-4">
            <h2 class="summary-title">Payroll Summary<?php echo $selectedPeriod !== '' ? ' - ' . safe($selectedPeriod) : ''; ?></h2>
            <div class="row g-3">
                <div class="col-sm-6 col-xl-3">
                    <div class="card h-100 p-3 border-0 bg-light">
                        <small class="text-muted">Total Staff</small>
                        <h3 class="mb-0 mt-2"><?php echo number_format($summaryStaff); ?></h3>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="card h-100 p-3 border-0 bg-light">
                        <small class="text-muted">Total Gross Pay</small>
                        <h3 class="mb-0 mt-2">KES <?php echo number_format((float)$summaryGross, 2); ?></h3>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="card h-100 p-3 border-0 bg-light">
                        <small class="text-muted">Total Advance</small>
                        <h3 class="mb-0 mt-2">KES <?php echo number_format((float)$summaryAdvance, 2); ?></h3>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="card h-100 p-3 border-0 bg-light">
                        <small class="text-muted">Total Net Pay</small>
                        <h3 class="mb-0 mt-2">KES <?php echo number_format((float)$summaryNet, 2); ?></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
